#!/usr/bin/env bash
# =============================================================================
# serve-blink-assets.sh
#
# Serve the Blink Shell assets — the custom font CSS and the custom colour
# theme — over HTTP so Blink can import them. Blink imports both fonts and
# themes from a URL (not a local file), so this starts a throwaway Python HTTP
# server rooted at this directory, prints the import URLs, and serves until you
# Ctrl-C.
#
# Assets (served from this directory):
#   jetbrains-mono-nerd-font-custom.css  -> Blink FONT, save as "JetBrainsMono NF"
#                                           (build artifact — generated by
#                                           custom-builds/nerd-fonts/build-updated-font.sh)
#   chezmoi-system.js                    -> Blink THEME (build artifact — generated
#                                           from theme.yaml by
#                                           custom-builds/theme/generate-theme.sh)
#
# MIME note: Python 3.12+ maps .js to "text/javascript", which Blink's THEME
# importer rejects ("Unsupported media type"). GitHub's raw server (which Blink
# accepts) returns "text/plain", so we force .js -> text/plain below.
#
# Usage:
#   ./serve-blink-assets.sh [port]      # default port 8000; if the requested
#                                        # port is already listening, walks up
#                                        # to the first free port and announces
#                                        # the substitution (never silently
#                                        # collides with another service).
#
# In Blink (Settings -> Appearance):
#   Fonts  -> New Font  -> paste the printed .css URL -> save as "JetBrainsMono NF"
#   Themes -> New Theme -> paste the printed .js  URL -> save and select it
#
# Override the served directory with BLINK_ASSETS_DIR (defaults to this script's
# own directory).
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd -P )"
ASSETS_DIR="${BLINK_ASSETS_DIR:-${SCRIPT_DIR}}"
PORT="${1:-8000}"

FONT_CSS="jetbrains-mono-nerd-font-custom.css"
THEME_JS="chezmoi-system.js"

# If the requested port is already listening, walk upward to the first free one
# so this script never silently collides with another service on the same port
# (e.g. a colliding 127.0.0.1:8000 listener intercepted requests and Blink got
# a 404 instead of the font). A caller-supplied port is honoured unless it is
# taken; the chosen port is announced below so the import URLs stay correct.
port_is_listening() {
  # lsof on macOS, ss on Linux, netstat fallback.
  if command -v lsof >/dev/null 2>&1; then
    lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
  elif command -v ss >/dev/null 2>&1; then
    ss -ltn "sport = :$1" >/dev/null 2>&1
  elif command -v netstat >/dev/null 2>&1; then
    netstat -ltn 2>/dev/null | grep -Eq "[.:]$1[[:space:]]+.*LISTEN"
  else
    return 1  # can't tell — assume free rather than blocking forever
  fi
}
REQUESTED_PORT="${PORT}"
while port_is_listening "${PORT}"; do
  PORT=$(( PORT + 1 ))
done
if [[ "${PORT}" != "${REQUESTED_PORT}" ]]; then
  printf 'note: port %s already in use; serving on %s instead.\n\n' \
    "${REQUESTED_PORT}" "${PORT}" >&2
fi

if [[ ! -d "${ASSETS_DIR}" ]]; then
  printf 'error: %s does not exist.\n' "${ASSETS_DIR}" >&2
  exit 1
fi

# The theme is committed; the font CSS is a build artifact. If the font is
# missing, the user hasn't generated it yet — point them at the builder rather
# than silently serving only the theme.
REPO_ROOT="$( cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd -P )"
BUILD_SCRIPT="${REPO_ROOT}/custom-builds/nerd-fonts/build-updated-font.sh"
if [[ ! -f "${ASSETS_DIR}/${FONT_CSS}" ]]; then
  printf 'warning: %s not found in %s.\n' "${FONT_CSS}" "${ASSETS_DIR}" >&2
  printf '         The font is a build artifact, not committed. Generate it with:\n\n' >&2
  if [[ -x "${BUILD_SCRIPT}" ]]; then
    printf '           %s\n\n' "${BUILD_SCRIPT}" >&2
  else
    printf '           custom-builds/nerd-fonts/build-updated-font.sh\n\n' >&2
  fi
  printf '         then re-run this script to serve the font alongside the theme.\n' >&2
  printf '         (Serving the theme only for now.)\n\n' >&2
fi

# At least one asset must be present, or there is nothing to import.
if [[ ! -f "${ASSETS_DIR}/${FONT_CSS}" && ! -f "${ASSETS_DIR}/${THEME_JS}" ]]; then
  printf 'error: neither %s nor %s found in %s; nothing to serve.\n' \
    "${FONT_CSS}" "${THEME_JS}" "${ASSETS_DIR}" >&2
  exit 1
fi

PYTHON="$(command -v python3 || command -v python || true)"
[[ -n "${PYTHON}" ]] || { printf 'error: python3 not found on PATH.\n' >&2; exit 1; }

# Blink runs on a separate device (iOS), so "localhost" would point at the
# device itself, not this machine — the import fails. Advertise a
# LAN-reachable address instead. The Python server already binds 0.0.0.0.

# The Bonjour/mDNS hostname (<name>.local), resolvable from other devices on
# the same network. Empty if it can't be determined.
bonjour_host() {
  if command -v scutil >/dev/null 2>&1; then
    local lh; lh="$(scutil --get LocalHostName 2>/dev/null || true)"
    [[ -n "${lh}" ]] && { printf '%s.local' "${lh}"; return; }
  fi
  # Linux / other: use the FQDN-ish hostname only if it already looks resolvable.
  if command -v hostname >/dev/null 2>&1; then
    local hn; hn="$(hostname 2>/dev/null || true)"
    [[ "${hn}" == *.* ]] && printf '%s' "${hn}"
  fi
}

# The current LAN IPv4. Empty if it can't be determined.
lan_ip() {
  local ip iface
  if command -v ipconfig >/dev/null 2>&1; then            # macOS
    for iface in en0 en1 en2 en3 en4; do
      ip="$(ipconfig getifaddr "${iface}" 2>/dev/null || true)"
      [[ -n "${ip}" ]] && { printf '%s' "${ip}"; return; }
    done
  fi
  if command -v hostname >/dev/null 2>&1; then             # Linux
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
    [[ -n "${ip}" ]] && { printf '%s' "${ip}"; return; }
  fi
}

# `|| true`: the detectors return non-zero when nothing is found, which would
# trip `set -e` on these assignments. The || also suspends `set -e` inside the
# function, so internal probe failures can't abort the script either.
HOST_NAME="$(bonjour_host || true)"
HOST_IP="$(lan_ip || true)"
# Prefer the hostname; fall back to the IP. Last resort: localhost (and warn).
HOST="${HOST_NAME:-${HOST_IP:-localhost}}"
if [[ "${HOST}" == "localhost" ]]; then
  printf 'warning: could not detect a LAN hostname/IP; Blink on another device\n'
  printf '         will NOT be able to reach http://localhost:%s/.\n\n' "${PORT}"
fi

# Print the import URL for each asset that is actually present, labelled by the
# Blink surface it goes into.
print_urls() {  # print_urls <host>
  [[ -f "${ASSETS_DIR}/${FONT_CSS}" ]] && \
    printf '  Font  -> http://%s:%s/%s\n' "$1" "${PORT}" "${FONT_CSS}"
  [[ -f "${ASSETS_DIR}/${THEME_JS}" ]] && \
    printf '  Theme -> http://%s:%s/%s\n' "$1" "${PORT}" "${THEME_JS}"
}

printf 'Serving %s on http://%s:%s/\n\n' "${ASSETS_DIR}" "${HOST}" "${PORT}"
printf 'Import these URLs into Blink (Settings -> Appearance):\n'
print_urls "${HOST}"
# If we advertised the .local hostname but also have an IP, offer it as a
# fallback — Bonjour resolution is flaky on some iOS networks.
if [[ -n "${HOST_NAME}" && -n "${HOST_IP}" && "${HOST}" == "${HOST_NAME}" ]]; then
  printf '\nIf the .local name does not resolve, use the IP instead:\n'
  print_urls "${HOST_IP}"
fi
printf '\nPress Ctrl-C to stop.\n\n'

# Serve with a corrected MIME map: .js as text/plain (Blink's theme importer
# rejects text/javascript), .css as text/css. ThreadingHTTPServer + 0.0.0.0 so
# the iOS device on the LAN can reach it.
exec "${PYTHON}" -c '
import sys, functools
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

directory, port = sys.argv[1], int(sys.argv[2])
handler = SimpleHTTPRequestHandler
handler.extensions_map[".js"] = "text/plain"   # Blink rejects text/javascript
handler.extensions_map[".css"] = "text/css"
ThreadingHTTPServer.allow_reuse_address = True
httpd = ThreadingHTTPServer(("0.0.0.0", port),
                            functools.partial(handler, directory=directory))
httpd.serve_forever()
' "${ASSETS_DIR}" "${PORT}"
