# Tests for home/dot_local/bin/executable_system-service-systemd.
#
# systemctl is stubbed on PATH so the suite never touches a real user
# manager (and stays runnable on macOS). The stub honours:
#   $STUB_SHOW     — body printed for `systemctl --user show ...`
#   $STUB_CALLS    — file path; every invocation's argv is appended to it
# Manifest and unit dir point at per-example sandboxes via SVCFILE and
# SYSTEMD_USER_DIR (the launchd suite's LAUNCH_AGENTS pattern).

Describe 'system-service-systemd'
  SYSTEMD_BIN="$SHELLSPEC_PROJECT_ROOT/home/dot_local/bin/executable_system-service-systemd"
  export SYS_PKG_LIB="$SHELLSPEC_PROJECT_ROOT/home/dot_local/lib"

  setup() {
    TEST_TMP="$(mktemp -d)"
    STUB_DIR="$TEST_TMP/bin"
    mkdir -p "$STUB_DIR" "$TEST_TMP/units"
    export SYSTEMD_USER_DIR="$TEST_TMP/units"
    export SVCFILE="$TEST_TMP/services.toml"
    export STUB_CALLS="$TEST_TMP/systemctl.calls"
    cat >"$STUB_DIR/systemctl" <<'STUB'
#!/bin/sh
printf '%s\n' "$*" >>"${STUB_CALLS:-/dev/null}"
case "$*" in
  *" show "*)
    printf '%s\n' "$STUB_SHOW"
    ;;
  *"is-enabled"*)
    [ "${STUB_ENABLED:-no}" = yes ] && { echo enabled; exit 0; }
    echo disabled; exit 1
    ;;
  *) : ;;   # start/stop/restart/enable/disable/daemon-reload — succeed silently
esac
exit 0
STUB
    chmod +x "$STUB_DIR/systemctl"
    export PATH="$STUB_DIR:$PATH"
  }
  cleanup() {
    rm -rf "$TEST_TMP"
    unset STUB_SHOW STUB_ENABLED STUB_CALLS
  }
  BeforeEach 'setup'
  AfterEach 'cleanup'

  # A rendered entry and an adopted entry, used across the suite.
  write_manifest() {
    cat >"$SVCFILE" <<'TOML'
[demo]
description = "demo daemon"
cmd = ["/bin/demo-daemon", "--flag", "a b"]
keep_alive = true
run_at_load = true

[clipboard-bridge]
unit = "clipboard-bridge.socket"
description = "clipboard bridge socket"
TOML
  }

  Describe 'status'
    It 'reports an active service as running'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=active\nSubState=running\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" status demo
      The output should equal "running"
      The status should be success
    End

    It 'reports an active socket/oneshot (SubState listening/exited) as running'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=active\nSubState=listening\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" status clipboard-bridge
      The output should equal "running"
    End

    It 'reports a cleanly inactive service as stopped'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=inactive\nSubState=dead\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" status demo
      The output should equal "stopped"
    End

    It 'reports a failed service as error'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=failed\nSubState=failed\nResult=exit-code\nExecMainStatus=2')"
      When run zsh "$SYSTEMD_BIN" status demo
      The output should equal "error"
    End

    It 'reports a not-found unit as none'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=not-found\nActiveState=inactive\nSubState=dead\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" status demo
      The output should equal "none"
    End

    It 'targets the adopted unit name, not a generated one'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=active\nSubState=listening\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" status clipboard-bridge
      The output should equal "running"
      The status should be success
      The contents of file "$STUB_CALLS" should include "clipboard-bridge.socket"
    End
  End

  Describe 'declared'
    It 'prints the manifest keys'
      write_manifest
      When run zsh "$SYSTEMD_BIN" declared
      The line 1 of output should equal "clipboard-bridge"
      The line 2 of output should equal "demo"
    End
  End

  Describe 'render'
    It 'renders the full schema to a systemd unit'
      write_manifest
      When run zsh "$SYSTEMD_BIN" render demo
      The output should include "# Generated by system-service-systemd"
      The output should include "Description=demo daemon"
      The output should include 'ExecStart="/bin/demo-daemon" "--flag" "a b"'
      The output should include "Restart=always"
      The output should include "WantedBy=default.target"
    End

    It 'renders optional keys only when present'
      cat >"$SVCFILE" <<'TOML'
[minimal]
cmd = ["/bin/true"]
TOML
      When run zsh "$SYSTEMD_BIN" render minimal
      The output should include "Restart=no"
      The output should not include "WantedBy"
      The output should not include "WorkingDirectory"
      The output should not include "Environment="
    End

    It 'expands tilde and escapes percent in paths and env'
      cat >"$SVCFILE" <<'TOML'
[pathy]
cmd = ["/bin/true"]
working_dir = "~/work"
log_path = "~/logs/pathy.log"
[pathy.env]
FMT = "100%"
TOML
      When run zsh "$SYSTEMD_BIN" render pathy
      The output should include "WorkingDirectory=$HOME/work"
      The output should include "StandardOutput=append:$HOME/logs/pathy.log"
      The output should include "Environment=\"FMT=100%%\""
    End

    It 'refuses to render an adopted entry'
      write_manifest
      When run zsh "$SYSTEMD_BIN" render clipboard-bridge
      The status should be failure
      The stderr should include "adopted"
    End

    It 'refuses launchd scheduling keys'
      cat >"$SVCFILE" <<'TOML'
[timered]
cmd = ["/bin/true"]
start_interval = 1800
TOML
      When run zsh "$SYSTEMD_BIN" render timered
      The status should be failure
      The stderr should include "timer"
    End

    It 'expands tilde in env values, not just paths'
      cat >"$SVCFILE" <<'TOML'
[envtilde]
cmd = ["/bin/true"]
[envtilde.env]
DATA_DIR = "~/data"
TOML
      When run zsh "$SYSTEMD_BIN" render envtilde
      The output should include "Environment=\"DATA_DIR=$HOME/data\""
    End

    It 'dies when a section declares both unit and cmd'
      cat >"$SVCFILE" <<'TOML'
[confused]
unit = "confused.service"
cmd = ["/bin/true"]
TOML
      When run zsh "$SYSTEMD_BIN" render confused
      The status should be failure
      The stderr should include "BOTH"
    End
  End

  Describe 'start/stop/restart'
    It 'start on a rendered entry writes the unit, reloads, enables, restarts'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=inactive\nSubState=dead\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" start demo
      The status should be success
      The output should include "started"
      The path "$SYSTEMD_USER_DIR/com.system-service.demo.service" should be file
      The contents of file "$STUB_CALLS" should include "daemon-reload"
      The contents of file "$STUB_CALLS" should include "enable"
      The contents of file "$STUB_CALLS" should include "restart"
    End

    It 'start on an unchanged unit skips daemon-reload'
      write_manifest
      zsh "$SYSTEMD_BIN" render demo >"$SYSTEMD_USER_DIR/com.system-service.demo.service"
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=inactive\nSubState=dead\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" start demo
      The status should be success
      The output should include "started"
      The contents of file "$STUB_CALLS" should not include "daemon-reload"
      The contents of file "$STUB_CALLS" should include "start"
    End

    It 'start on an adopted entry only enables and starts (never writes)'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=inactive\nSubState=dead\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" start clipboard-bridge
      The status should be success
      The output should include "started"
      The path "$SYSTEMD_USER_DIR/clipboard-bridge.socket" should not be exist
      The contents of file "$STUB_CALLS" should include "enable"
      The contents of file "$STUB_CALLS" should include "clipboard-bridge.socket"
    End

    It 'stop stops and disables'
      write_manifest
      export STUB_ENABLED=yes
      When run zsh "$SYSTEMD_BIN" stop demo
      The status should be success
      The output should include "stopped"
      The contents of file "$STUB_CALLS" should include "stop"
      The contents of file "$STUB_CALLS" should include "disable"
    End
  End

  Describe 'list / info / matching'
    It 'lists every declared entry as Service<TAB>Status<TAB>User<TAB>File'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=active\nSubState=running\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" list
      The line 1 of output should equal "$(printf 'clipboard-bridge\trunning\t%s\t%s/clipboard-bridge.socket' "$(id -un)" "$SYSTEMD_USER_DIR")"
      The line 2 of output should equal "$(printf 'demo\trunning\t%s\t%s/com.system-service.demo.service' "$(id -un)" "$SYSTEMD_USER_DIR")"
    End

    It 'info shows the manifest entry and unit path'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=active\nSubState=running\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" info demo
      The output should include "com.system-service.demo.service"
      The output should include "status:   running"
      The output should include '"cmd"'
    End

    It 'matching finds by key and by cmd0 basename; adopted match by key only'
      write_manifest
      When run zsh "$SYSTEMD_BIN" matching demo-daemon
      The output should equal "demo"
    End
  End

  Describe 'sync'
    It 'installs a fresh rendered entry and starts it (run_at_load)'
      write_manifest
      export STUB_SHOW="$(printf 'LoadState=not-found\nActiveState=inactive\nSubState=dead\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" sync
      The status should be success
      The output should include "Syncing"
      The path "$SYSTEMD_USER_DIR/com.system-service.demo.service" should be file
      The contents of file "$STUB_CALLS" should include "daemon-reload"
      The contents of file "$STUB_CALLS" should include " start "
    End

    It 'restarts a drifted unit only when it was running'
      write_manifest
      printf 'stale unit text\n' >"$SYSTEMD_USER_DIR/com.system-service.demo.service"
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=active\nSubState=running\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" sync
      The status should be success
      The output should include "Syncing"
      The contents of file "$STUB_CALLS" should include "restart"
    End

    It 'leaves a drifted-but-stopped unit stopped'
      write_manifest
      printf 'stale unit text\n' >"$SYSTEMD_USER_DIR/com.system-service.demo.service"
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=inactive\nSubState=dead\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" sync
      The status should be success
      The output should include "Syncing"
      The contents of file "$STUB_CALLS" should not include " restart "
    End

    It 'sweeps orphaned generated units but never adopted files'
      write_manifest
      printf 'orphan\n' >"$SYSTEMD_USER_DIR/com.system-service.ghost.service"
      printf 'adopted file\n' >"$SYSTEMD_USER_DIR/clipboard-bridge.socket"
      export STUB_SHOW="$(printf 'LoadState=loaded\nActiveState=active\nSubState=running\nResult=success\nExecMainStatus=0')"
      When run zsh "$SYSTEMD_BIN" sync
      The status should be success
      The output should include "removing orphan"
      The path "$SYSTEMD_USER_DIR/com.system-service.ghost.service" should not be exist
      The path "$SYSTEMD_USER_DIR/clipboard-bridge.socket" should be file
    End
  End
End
