[tools]
# Programming languages
go = "latest"
java = "latest"
kotlin = "latest"
lua = "5.1"
node = "latest"
python = "latest"
rust = "latest"

# Tools
cmake = "latest"
just = "latest"
ninja = "latest"
uv = "latest"

[settings]
[settings.python]
uv_venv_auto = true
