# ~/.gnupg/gpg.conf

default-key A9C4A3D8CA995D91
auto-key-locate keyserver

# Keyserver settings
# The server that --recv-keys, --send-keys, and --search-keys will communicate with
# keyserver hkps://hkps.pool.sks-keyservers.net
keyserver hkps://keys.openpgp.org

keyserver-options no-honor-keyserver-url include-revoked auto-key-retrieve
