abbr "gb"="git branch -v"
abbr "gba"="git branch -av"
abbr "gc"="git commit -v"
abbr "gca"="git commit -v -a"
abbr "gd"="git dv"
abbr "gdf"="git diff --name-only"
abbr "gp"="git push"
abbr "grv"="git remote -v"
abbr "gst"="git status --short"
abbr "gu"="git pull"
abbr "lg"="lazygit"
abbr "l"="ls -1"
abbr "la"="ls -a"
abbr "ll"="ls -l"
abbr "lla"="ls -la"
abbr "lsg"="ls --git --git-ignore"
abbr "lt"="ls --tree"
abbr "ssh-x"="ssh -o CompressionLevel=9 -c arcfour,blowfish-cbc -YC"
