--- apps/clipboard-history.lua
--- Universal clipboard history store + macOS capture.
---
--- Backs the universal-clipboard project
--- (docs/clipboard-universal-project.md §5, §6): a single SQLite WAL store at
---   ${XDG_DATA_HOME:-~/.local/share}/pick-clipboard/history.db
--- shared by this macOS capture watcher, the `pick-clipboard` fzf picker
--- (pick silo), and the Hammerspoon chooser (Phase 4). Sensitive
--- pasteboards (password-manager apps, `org.nspasteboard.ConcealedType` /
--- `TransientType` / `AutoGeneratedType`) are skipped BEFORE any storage, so
--- they never enter history.
---
--- Schema (spec §5):
---   clips(id, text_preview, text_plain, len, first_ts, last_ts, source_app,
---         type_kind, origin, regtype, pinned, type_hash)
---   clip_types(clip_id, uti, blob)   -- one row per UTI, full rich payload
--- `type_hash` is the dedup index for spec §5's "Dedup on a hash of the
--- type-set; re-copy bumps last_ts" — sha256 of the sorted (UTI=blob) pairs.
--- It is an implementation column; readers select the documented columns.
---
--- Phase 2 scope: store + macOS `hs.pasteboard.watcher` capture. The chooser
--- (§10), bridge evolution (§11), and regtype / current-regtype tracking (§9)
--- land in later phases. Here every captured row is `origin='local'` and
--- `regtype=NULL` (the watcher can't see that a copy came from remote nvim).
---
--- API:
---   local ch = require("apps.clipboard-history")
---   ch.setup()        -- open DB, create schema, start the watcher
---   ch.cleanup()      -- stop watcher, close DB (register with lifecycle)
---   ch.capture_now()  -- force a read+store cycle (used by tests)

local M = {}

local sqlite3   = require("hs.sqlite3")
local pasteboard = hs.pasteboard
local hash       = hs.hash

-- Sensitive NSPasteboard concealment UTIs — skip before storing (spec §15).
local SENSITIVE_UTIS = {
  ["org.nspasteboard.ConcealedType"] = true,
  ["org.nspasteboard.TransientType"] = true,
  ["org.nspasteboard.AutoGeneratedType"] = true,
}

-- Frontmost-app deny-list: never capture from password managers (spec §6).
local DENY_APPS = {
  ["Keychain Access"] = true,
  ["1Password"]       = true,
  ["1Password 7"]     = true,
  ["1Password 8"]     = true,
  ["Bitwarden"]       = true,
  ["Dashlane"]        = true,
  ["KeePassXC"]       = true,
}

local MAX_ROWS          = 1000                 -- retention: ≤1000 rows (spec §5)
local MAX_IMAGE_BYTES   = 5 * 1024 * 1024      -- skip images > ~5 MB (spec §5)
local MAX_STORE_BYTES   = 200 * 1024 * 1024    -- total-store cap (oldest dropped)

local db                   -- sqlite3 handle (kept open; WAL -> readers don't block)
local watcher
local last_change = 0

local function data_dir()
  return os.getenv("XDG_DATA_HOME") or (os.getenv("HOME") or "") .. "/.local/share"
end

local function db_path()
  return data_dir() .. "/pick-clipboard/history.db"
end

local function now_ts()
  return hs.timer.secondsSinceEpoch()
end

-- Classify the type_kind badge (spec §5: text|rtf|html|image|files|mixed)
-- from the UTI set. Rich kinds are counted; 0 -> text, 1 -> that kind,
-- >1 -> mixed.
local function classify(utis)
  local has = {}
  for _, u in ipairs(utis) do has[u] = true end
  local rich = {}
  if has["public.rtf"] or has["NeXT RTFD pasteboard type"] or has["Apple RTFD"] then rich[#rich + 1] = "rtf" end
  if has["public.html"] then rich[#rich + 1] = "html" end
  if has["public.png"] or has["public.jpeg"] or has["public.tiff"]
     or has["com.compuserve.gif"] or has["public.image"] then rich[#rich + 1] = "image" end
  if has["public.file-url"] or has["NSFilenamesPboardType"] then rich[#rich + 1] = "files" end
  if #rich == 0 then return "text" end
  if #rich == 1 then return rich[1] end
  return "mixed"
end

-- sha256 of the sorted (uti=blob) set — the dedup key. Binary-safe.
local function type_hash(data_by_uti)
  local utis = {}
  local total = 0
  for uti, blob in pairs(data_by_uti) do
    utis[#utis + 1] = uti
    total = total + #(blob or "")
  end
  table.sort(utis)
  -- For very large single-image clips this still hashes the bytes; sha256
  -- is C-fast. The cap below skips oversized images before we get here.
  local parts = {}
  for _, uti in ipairs(utis) do
    parts[#parts + 1] = uti .. "=" .. (data_by_uti[uti] or "")
  end
  return hash.SHA256(table.concat(parts, "\n")), total
end

-- First line, newlines collapsed, truncated for the preview column.
local function preview_of(text)
  if text == nil then return nil end
  local first = text:match("^[^\r\n]*") or ""
  if #first > 100 then first = first:sub(1, 100) .. "…" end
  return first
end

local function exec(sql)
  local rc = db:exec(sql)
  if rc ~= sqlite3.OK then
    hs.printf("clipboard-history: exec failed rc=%d: %s", rc or -1, sql)
  end
  return rc
end

local function ensure_schema()
  exec("PRAGMA journal_mode=WAL;")
  exec("PRAGMA synchronous=NORMAL;")
  exec([[CREATE TABLE IF NOT EXISTS clips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text_preview TEXT,
    text_plain TEXT,
    len INTEGER,
    first_ts REAL,
    last_ts REAL,
    source_app TEXT,
    type_kind TEXT,
    origin TEXT,
    regtype TEXT,
    pinned INTEGER DEFAULT 0,
    type_hash TEXT
  );]])
  exec([[CREATE TABLE IF NOT EXISTS clip_types (
    clip_id INTEGER,
    uti TEXT,
    blob BLOB,
    PRIMARY KEY (clip_id, uti)
  );]])
  exec("CREATE INDEX IF NOT EXISTS idx_clips_type_hash ON clips(type_hash);")
  exec("CREATE INDEX IF NOT EXISTS idx_clips_last_ts ON clips(last_ts DESC);")
  exec("CREATE INDEX IF NOT EXISTS idx_clips_pinned_ts ON clips(pinned DESC, last_ts DESC);")
end

-- Drop oldest non-pinned rows until under both the row and byte caps.
local function enforce_retention()
  exec("DELETE FROM clips WHERE id IN ("
       .. " SELECT id FROM clips WHERE pinned=0 ORDER BY last_ts ASC "
       .. " LIMIT (SELECT MAX(0, COUNT(*) - " .. MAX_ROWS .. ") FROM clips)"
       .. ");")
  -- total-store byte cap: sum of clip_types.blob over the whole store.
  local st = assert(db:prepare(
    "SELECT (SELECT COUNT(*) FROM clips) AS n, "
    .. " (SELECT COALESCE(SUM(length(blob)),0) FROM clip_types) AS bytes;"))
  if st:step() == sqlite3.ROW then
    local n = st:get_value(0) or 0
    local bytes = st:get_value(1) or 0
    st:finalize()
    if bytes > MAX_STORE_BYTES then
      exec("DELETE FROM clips WHERE pinned=0 AND id IN ("
           .. " SELECT clip_id FROM clip_types GROUP BY clip_id "
           .. " ORDER BY (SELECT last_ts FROM clips c WHERE c.id=clip_id) ASC "
           .. " LIMIT " .. math.max(1, n - MAX_ROWS / 2)
           .. ");")
    end
  else
    st:finalize()
  end
  -- orphaned clip_types rows (cascade by hand: SQLite lacks FK enforcement
  -- unless PRAGMA foreign_keys=ON, which we don't rely on across processes).
  exec("DELETE FROM clip_types WHERE clip_id NOT IN (SELECT id FROM clips);")
end

-- Store one capture. Returns the clip id, or nil if skipped.
function M.capture_now()
  if not db then return nil end

  local types = pasteboard.allContentTypes() or {}
  local item_utis = types[1] or {}
  if #item_utis == 0 then return nil end

  -- Sensitive-type skip (spec §15): never store concealed/transient clips.
  for _, uti in ipairs(item_utis) do
    if SENSITIVE_UTIS[uti] then return nil end
  end

  -- App deny-list (spec §6).
  local app = hs.application.frontmostApplication()
  local app_name = app and app:name() or nil
  if app_name and DENY_APPS[app_name] then return nil end

  local data_by_uti = pasteboard.readAllData() or {}
  if next(data_by_uti) == nil then return nil end

  local kind = classify(item_utis)

  -- Skip oversized images (spec §5: "skip images > ~5 MB").
  if kind == "image" or kind == "mixed" then
    for uti, blob in pairs(data_by_uti) do
      if uti:find("image", 1, true) and #(blob or "") > MAX_IMAGE_BYTES then
        return nil
      end
    end
  end

  local th, total_bytes = type_hash(data_by_uti)
  local plain = data_by_uti["public.utf8-plain-text"]
                or data_by_uti["public.text"]
                or data_by_uti["NSStringPboardType"]
  local preview = preview_of(plain)
  if not preview then
    -- non-text clip: synthesize a short badge from the kind + a payload hint
    if kind == "image" then preview = "[image]"
    elseif kind == "files" then preview = "[files]"
    elseif kind == "rtf" then preview = "[rtf]"
    elseif kind == "html" then preview = "[html]"
    else preview = "[" .. kind .. "]" end
  end
  local len_val = plain and #plain or total_bytes
  local ts = now_ts()

  -- Dedup on type_hash: bump last_ts + refresh source_app/preview if present.
  local dup = assert(db:prepare(
    "SELECT id FROM clips WHERE type_hash=? AND pinned=0 "
    .. " ORDER BY id DESC LIMIT 1;"))
  dup:bind(1, th)
  local existing_id
  if dup:step() == sqlite3.ROW then existing_id = dup:get_value(0) end
  dup:finalize()

  if existing_id then
    local up = assert(db:prepare(
      "UPDATE clips SET last_ts=?, source_app=?, text_preview=?, text_plain=?, "
      .. " len=?, type_kind=? WHERE id=?;"))
    up:bind(1, ts); up:bind(2, app_name); up:bind(3, preview); up:bind(4, plain)
    up:bind(5, len_val); up:bind(6, kind); up:bind(7, existing_id)
    up:step(); up:finalize()
    enforce_retention()
    return existing_id
  end

  -- New row.
  local ins = assert(db:prepare(
    "INSERT INTO clips (text_preview, text_plain, len, first_ts, last_ts, "
    .. " source_app, type_kind, origin, regtype, pinned, type_hash) "
    .. " VALUES (?,?,?,?,?,?,?,  'local', NULL, 0, ?);"))
  ins:bind(1, preview); ins:bind(2, plain); ins:bind(3, len_val)
  ins:bind(4, ts); ins:bind(5, ts); ins:bind(6, app_name)
  ins:bind(7, kind); ins:bind(8, th)
  ins:step(); ins:finalize()
  local new_id = db:last_insert_rowid()

  -- Rich payloads: one clip_types row per UTI.
  for uti, blob in pairs(data_by_uti) do
    if blob ~= nil then
      local ct = assert(db:prepare(
        "INSERT OR REPLACE INTO clip_types (clip_id, uti, blob) VALUES (?,?,?);"))
      ct:bind(1, new_id); ct:bind(2, uti); ct:bind_blob(3, blob)
      ct:step(); ct:finalize()
    end
  end

  enforce_retention()
  return new_id
end

-- Watcher callback: ignore the string arg (nil for non-text clips) and do
-- our own full read. Guard against re-processing the same changeCount.
local function on_change(_v)
  local cc = pasteboard.changeCount()
  if cc == last_change then return end
  last_change = cc
  M.capture_now()
end

function M.setup()
  if db then return end
  os.execute("mkdir -p " .. (data_dir() .. "/pick-clipboard"):gsub("'", [["'"]]))
  db = sqlite3.open(db_path())
  if type(db) ~= "userdata" then
    hs.printf("clipboard-history: could not open %s", db_path())
    db = nil
    return
  end
  ensure_schema()
  last_change = pasteboard.changeCount()
  pasteboard.watcher.interval(0.5)
  watcher = pasteboard.watcher.new(on_change)
  -- `new` starts the watcher already; nothing else to do.
end

function M.cleanup()
  if watcher then watcher:stop(); watcher = nil end
  if db then db:close(); db = nil end
end

-- Test/inspection helpers (not used in production paths).
function M._db_path() return db_path() end
function M._row_count()
  if not db then return nil end
  local s = assert(db:prepare("SELECT COUNT(*) FROM clips;"))
  local n
  if s:step() == sqlite3.ROW then n = s:get_value(0) end
  s:finalize()
  return n
end

--------------------------------------------------------------------------------
-- Phase 4: hs.chooser GUI picker + rich restore (spec §10)
--------------------------------------------------------------------------------
-- Bound globally to Cmd+Shift+V (see init.lua kb.setup). Reads the same
-- history.db on each open; selecting a row restores the full rich pasteboard
-- (all UTIs via hs.pasteboard.writeAllData) and posts ⌘V into the app that had
-- focus before the chooser opened. hs.chooser's built-in globalCallback already
-- saves frontmostWindow() on willOpen and refocuses it on didClose, so we only
-- restore + schedule the ⌘V keystroke for just after didClose.
--
-- Raycast also registers Cmd+Shift+V today (spec §10 accepts that shadow);
-- if Raycast intercepts first the chooser won't open — disable Raycast's
-- chord or remap this binding if you want the chooser on that key.

local chooser

-- Restore a clip's full rich pasteboard by id (all UTI->blob rows from
-- clip_types). Returns true on success. Also bumps last_ts (spec §10
-- "re-bump last_ts on pick"). The pasteboard write bumps changeCount, so the
-- watcher will re-observe it (dedup bumps the same row again — harmless).
function M.restore_by_id(id)
  if not db or not id then return false end
  local s = assert(db:prepare("SELECT uti, blob FROM clip_types WHERE clip_id=?;"))
  s:bind(1, id)
  local data = {}
  while s:step() == sqlite3.ROW do
    data[s:get_value(0)] = s:get_value(1)  -- uti -> blob (Lua string)
  end
  s:finalize()
  if next(data) == nil then
    -- No rich payload (e.g. a laptop-ref text-only row): fall back to text_plain.
    local t = assert(db:prepare("SELECT text_plain FROM clips WHERE id=?;"))
    t:bind(1, id)
    local plain
    if t:step() == sqlite3.ROW then plain = t:get_value(0) end
    t:finalize()
    if not plain then return false end
    pasteboard.setContents(plain)
  else
    pasteboard.writeAllData(data)
  end
  local b = db:prepare("UPDATE clips SET last_ts=? WHERE id=?;")
  if b then b:bind(1, now_ts()); b:bind(2, id); b:step(); b:finalize() end
  return true
end

-- Build the chooser rows from the store: top 200 by pinned/last_ts, local +
-- remote-own only (laptop-ref rows can't be rich-restored on this machine).
local function chooser_rows()
  if not db then return {} end
  local s = assert(db:prepare(
    "SELECT id, text_preview, type_kind, source_app, len, pinned, "
    .. " CAST(strftime('%s','now') AS INT) - CAST(last_ts AS INT) AS age "
    .. " FROM clips WHERE origin IN ('local','remote-own') "
    .. " ORDER BY pinned DESC, last_ts DESC LIMIT 200;"))
  local rows = {}
  while s:step() == sqlite3.ROW do
    local id      = s:get_value(0)
    local preview = s:get_value(1)
    local kind    = s:get_value(2) or "text"
    local app     = s:get_value(3) or "?"
    local len     = s:get_value(4) or 0
    local pinned  = s:get_value(5) or 0
    local age     = s:get_value(6) or 0
    local age_s = age < 60 and (age .. "s")
      or  age < 3600 and (math.floor(age / 60) .. "m")
      or  age < 86400 and (math.floor(age / 3600) .. "h")
      or  (math.floor(age / 86400) .. "d")
    rows[#rows + 1] = {
      text = (pinned == 1 and " " or "") .. (preview or ("[" .. kind .. "]")),
      subText = string.format("· %dc · %s · %s · %s", len, app, age_s, kind),
      id = id, kind = kind, pinned = pinned,
    }
  end
  s:finalize()
  return rows
end

local function chooser_complete(row)
  if not row or row.id == nil then return end  -- cancelled
  M.restore_by_id(row.id)
  -- Post ⌘V just after the chooser's didClose refocuses the prior app.
  hs.timer.doAfter(0.12, function() hs.eventtap.keyStroke({ "cmd" }, "v") end)
end

-- Public entrypoint (bound to Cmd+Shift+V in init.lua). Lazily builds the
-- chooser, refreshes its rows from the store, and shows it.
function M.show_chooser()
  if not db then return end
  if not chooser then
    chooser = hs.chooser.new(chooser_complete)
    chooser:placeholderText("Clipboard history")
    chooser:searchSubText(true)
    chooser:choices(chooser_rows)
    chooser:rows(10)
  end
  chooser:refreshChoicesCallback(true)
  chooser:show()
end

return M
