--- apps/clipboard-history.lua
--- Universal clipboard history store + macOS capture.
---
--- Backs the universal-clipboard project
--- (docs/clipboard-universal-project.md §5, §6): a single SQLite WAL store at
---   ${XDG_DATA_HOME:-~/.local/share}/pick-clipboard/history.db
--- shared by this macOS capture watcher, the `pick-clipboard` fzf picker
--- (pick silo), and the Hammerspoon picker (Phase 4, apps/clipboard-picker.lua).
--- Sensitive
--- pasteboards (password-manager apps, `org.nspasteboard.ConcealedType` /
--- `TransientType` / `AutoGeneratedType`) are skipped BEFORE any storage, so
--- they never enter history.
---
--- Schema (spec §5):
---   clips(id, text_preview, text_plain, len, first_ts, last_ts, source_app,
---         source_bundle_id, type_kind, regtype, pinned, type_hash, source_host)
---   clip_types(clip_id, uti, blob)   -- one row per UTI, full rich payload
--- `type_hash` is the dedup index for spec §5's "Dedup on a hash of the
--- type-set; re-copy bumps last_ts" — sha256 of the sorted (UTI=blob) pairs.
--- It is an implementation column; readers select the documented columns.
--- `source_host` is the clip's origin (spec §11): local iff it equals this
--- machine's hostname. Self-contained clips — no `origin`/`ref_id` columns.
---
--- Phase 2 scope: store + macOS `hs.pasteboard.watcher` capture. The chooser
--- (§10) and bridge evolution (§11) land in later phases. A locally-captured
--- row carries `source_host` = this machine and `regtype=NULL` (the watcher
--- can't see that a copy came from remote nvim).
---
--- API:
---   local ch = require("apps.clipboard-history")
---   ch.setup()        -- open DB, create schema, start the watcher
---   ch.cleanup()      -- stop watcher, close DB (register with lifecycle)
---   ch.capture_now()  -- force a read+store cycle (used by tests)

local M = {}

local sqlite3   = require("hs.sqlite3")
local pasteboard = hs.pasteboard
local hash       = hs.hash

-- Sensitive NSPasteboard concealment UTIs — skip before storing (spec §15).
local SENSITIVE_UTIS = {
  ["org.nspasteboard.ConcealedType"] = true,
  ["org.nspasteboard.TransientType"] = true,
  ["org.nspasteboard.AutoGeneratedType"] = true,
}

-- Frontmost-app deny-list: never capture from password managers (spec §6).
local DENY_APPS = {
  ["Keychain Access"] = true,
  ["1Password"]       = true,
  ["1Password 7"]     = true,
  ["1Password 8"]     = true,
  ["Bitwarden"]       = true,
  ["Dashlane"]        = true,
  ["KeePassXC"]       = true,
}

local MAX_ROWS          = 1000                 -- retention: ≤1000 rows (spec §5)
local MAX_IMAGE_BYTES   = 5 * 1024 * 1024      -- skip images > ~5 MB (spec §5)
local MAX_STORE_BYTES   = 200 * 1024 * 1024    -- total-store cap (oldest dropped)

local db                   -- sqlite3 handle (kept open; WAL -> readers don't block)
local watcher
local last_change = 0

local function data_dir()
  return os.getenv("XDG_DATA_HOME") or (os.getenv("HOME") or "") .. "/.local/share"
end

local function db_path()
  return data_dir() .. "/pick-clipboard/history.db"
end

-- This machine's stable hostname, stamped on every clip captured here as its
-- origin (§11). A picker derives local/remote by comparing it to its own
-- hostname -- absolute provenance, not a per-DB direction flag. When a peer
-- clip is materialized here on use, it keeps ITS origin host, not this one.
-- Cached; the pickers read it the same way (scutil --get LocalHostName).
local MY_HOST
local function my_host()
  if MY_HOST == nil then
    local out = hs.execute("scutil --get LocalHostName 2>/dev/null") or ""
    MY_HOST = (out:gsub("%s+$", ""))
    if MY_HOST == "" then MY_HOST = (hs.host.localizedName() or "") end
  end
  return MY_HOST
end

-- The clipboard-bridge dispatcher's self-invalidating regtype file: line 1 is
-- the register type (v/l/b), line 2 is sha256(clipboard text). The nvim T op
-- writes it on copy; op_get_regtype trusts it only while the hash still matches
-- the live clipboard. We read it at capture (to record a clip's regtype) and
-- write it at restore (to reinstate one). Same path/format as the dispatcher.
local function regtype_file()
  local state = os.getenv("XDG_STATE_HOME") or ((os.getenv("HOME") or "") .. "/.local/state")
  return state .. "/pick-clipboard/current-regtype"
end

-- If the regtype file's hash matches this clip's plain text, the clip was just
-- set with that register type (e.g. an nvim block yank) — return it to record
-- on the row; else nil. sha256 is byte-identical to the dispatcher's shasum.
local function captured_regtype(plain)
  if not plain or plain == "" then return nil end
  local f = io.open(regtype_file(), "r")
  if not f then return nil end
  local rt = f:read("*l")
  local h = f:read("*l")
  f:close()
  if rt ~= "v" and rt ~= "l" and rt ~= "b" then return nil end
  if h and h == hash.SHA256(plain) then return rt end
  return nil
end

-- After restoring a clip, write its stored regtype + the hash of what actually
-- landed on the clipboard to the regtype file, so the next nvim paste (R op)
-- reinstates the register type. Hash the LIVE pasteboard (not the DB text_plain)
-- so it matches op_get_regtype's own sha256(pbpaste). No-op unless the clip
-- carries a v/l/b regtype (block-ness is a text concept). Call AFTER restoring.
local function write_regtype_for(id)
  if not db or not id then return end
  local s = db:prepare("SELECT regtype FROM clips WHERE id=?;")
  if not s then return end
  s:bind(1, id)
  local rt
  if s:step() == sqlite3.ROW then rt = s:get_value(0) end
  s:finalize()
  if rt ~= "v" and rt ~= "l" and rt ~= "b" then return end
  local cur = pasteboard.getContents()
  if not cur or cur == "" then return end
  local f = io.open(regtype_file(), "w")
  if f then f:write(rt .. "\n" .. hash.SHA256(cur) .. "\n"); f:close() end
end

local function now_ts()
  return hs.timer.secondsSinceEpoch()
end

-- Path/format shared with the dispatcher's O/N ops:
-- <host>\n<sha256hex>\n<epoch>[\nsuppress-echo]. The optional 4th line is the
-- one-shot echo-suppress flag written ONLY by the dispatcher's N op
-- (push-manifest, files-yazi design §5 T11 -- see the coordinator-authorized
-- contract note on clip::declare_origin_core in
-- ~/.local/libexec/clipboard-bridge-dispatch): N inserts its own
-- authoritative `files` store row, so this watcher must not also capture the
-- echoed pasteboard text (a duplicate row whose type_hash -- sha256 of the
-- UTI=blob pairs -- never matches the dispatcher's text-hash, so nothing
-- would ever dedup it, and its later capture timestamp would shadow the
-- manifest as the "latest" row). A 3-line file is exactly the pre-existing
-- O-op format.
-- The clipboard-mount M-op enrichment (clipboard-mount spec §6) arms the same
-- flag with the hash taken over the newline-joined MOUNT-MAPPED paths it just
-- wrote (a file-urls set has no text representation for the text-hash key) --
-- consumed by capture_now's files-suppress block below.
local function origin_file()
  local state = os.getenv("XDG_STATE_HOME") or ((os.getenv("HOME") or "") .. "/.local/state")
  return state .. "/pick-clipboard/current-origin"
end

local ORIGIN_TTL = 5 -- seconds; a declaration older than this is stale

-- Pure origin-file parser (deliberately no hs.*/upvalue dependencies beyond
-- ORIGIN_TTL, so it can be smoke-tested outside a live Hammerspoon capture
-- path -- exposed as M._parse_origin_file below). Returns nil when the file
-- is missing/mismatched/stale, else host plus a boolean suppress flag.
local function parse_origin_file(path, plain_sha256, now)
  local f = io.open(path, "r")
  if not f then return nil end
  local host = f:read("*l")
  local h = f:read("*l")
  local ts = tonumber(f:read("*l"))
  local flag = f:read("*l")
  f:close()
  if not host or host == "" then return nil end
  if not h or h ~= plain_sha256 then return nil end
  if not ts or (now - ts) > ORIGIN_TTL then return nil end
  return host, (flag == "suppress-echo")
end
M._parse_origin_file = parse_origin_file -- test seam only (pure function)

-- If a fresh declare-origin (O op, §23) matches this clip's plain text, the clip
-- was copied on that host (pbcopy / nvim y from a machine SSH'd into here) and
-- its bytes were pushed onto our pasteboard — return that host so the row is
-- stamped remote(host) instead of local. Mirrors captured_regtype; hash-keyed +
-- TTL'd so a later identical LOCAL copy isn't retroactively mis-tagged.
-- Second return: the N op's echo-suppress flag (see origin_file above);
-- capture_now consumes the file and skips the capture when it's set.
local function captured_origin(plain)
  if not plain or plain == "" then return nil end
  return parse_origin_file(origin_file(), hash.SHA256(plain), now_ts())
end

-- Classify the type_kind badge (spec §5: text|rtf|html|image|files|mixed)
-- from the UTI set. Rich kinds are counted; 0 -> text, 1 -> that kind,
-- >1 -> mixed.
local function classify(utis)
  local has = {}
  for _, u in ipairs(utis) do has[u] = true end
  local rich = {}
  if has["public.rtf"] or has["NeXT RTFD pasteboard type"] or has["Apple RTFD"] then rich[#rich + 1] = "rtf" end
  if has["public.html"] then rich[#rich + 1] = "html" end
  if has["public.png"] or has["public.jpeg"] or has["public.tiff"]
     or has["com.compuserve.gif"] or has["public.image"] then rich[#rich + 1] = "image" end
  if has["public.file-url"] or has["NSFilenamesPboardType"] then rich[#rich + 1] = "files" end
  if #rich == 0 then return "text" end
  if #rich == 1 then return rich[1] end
  return "mixed"
end

-- Refine the generic "files" kind into "file"/"directory" by resolving the
-- pasteboard's file URL to a real path and stat-ing it. macOS sometimes
-- vends an opaque file-reference URL (file:///.file/id=<vol>.<inode>, seen
-- from some Finder/system affordances) instead of a normal path-based one;
-- readURL()'s `filePath` field already resolves that in-process (verified
-- empirically against a captured file:///.file/id=... clip -- no need to
-- shell out to osascript/NSURL.filePathURL). Returns (kind, path) on
-- success, or (nil, nil) if resolution/stat fails -- caller keeps the
-- generic "files" kind. readURL() only ever inspects pasteboard item 1, so
-- the caller (capture_now) gates this to the genuinely single-path case
-- via ns_filenames() below -- a real multi-file clip never reaches here.
local function classify_file_or_directory()
  local r = pasteboard.readURL()
  local path = r and r.filePath
  if not path then return nil, nil end
  local mode = hs.fs.attributes(path, "mode")
  if mode == "directory" then return "directory", path end
  if mode == "file" then return "file", path end
  return nil, nil
end

-- Parse an NSFilenamesPboardType blob (binary or XML property list holding
-- an array of POSIX path strings -- macOS's legacy multi-file pasteboard
-- type, populated by Finder alongside public.file-url on a real multi- or
-- single-file copy) into a Lua array of paths, or nil if the blob is
-- missing/unparseable/empty. Pure -- test seam, see M._ns_filenames_from_blob.
local function ns_filenames_from_blob(blob)
  if not blob or blob == "" then return nil end
  local ok, names = pcall(hs.plist.readString, blob)
  if not ok or type(names) ~= "table" or #names == 0 then return nil end
  return names
end
M._ns_filenames_from_blob = ns_filenames_from_blob -- test seam only (pure function)

-- All paths of the current pasteboard's "files" clip, or nil if there's no
-- (parseable) NSFilenamesPboardType data. This -- NOT `data_by_uti`'s
-- allContentTypes()-derived key, and NOT pasteboard item count -- is the
-- only reliable way to tell a genuine multi-file clip from a single-file
-- one: verified empirically (R5a scratchpad) that once a clip has been
-- through M.restore_by_id (hs.pasteboard.writeAllData writes back a single
-- pasteboard item; it has no notion of "multiple items"), a *re-capture* of
-- that same clip shows its NSFilenamesPboardType blob wrapped in a
-- dynamically-generated "dyn.xxxx" UTI under allContentTypes()/
-- readAllData() -- so `data_by_uti["NSFilenamesPboardType"]` is nil and the
-- pasteboard's own item count is back down to 1, even for a 2-file clip.
-- hs.pasteboard.readDataForUTI(nil, "NSFilenamesPboardType"), asked by the
-- legacy type NAME rather than enumerated UTI, still resolves it correctly
-- via macOS's own legacy-type<->UTI bridging -- confirmed byte-identical to
-- the original blob in that exact restore-then-recapture scenario, which is
-- the case validated live in R5a (a restored 2-file clip mis-captured as
-- type_kind='file').
local function ns_filenames()
  local ok, blob = pcall(hs.pasteboard.readDataForUTI, nil, "NSFilenamesPboardType")
  if not ok then return nil end
  return ns_filenames_from_blob(blob)
end

-- Best-effort "is this JUST a URL, with nothing else" heuristic (used to
-- reclassify a text/html clip as "url"). Trimmed and anchored end-to-end:
-- scheme + "://" + no-whitespace, and nothing besides that in the string.
local function looks_like_bare_url(s)
  s = (s or ""):match("^%s*(.-)%s*$")
  return s ~= "" and s:match("^%a[%w+%.%-]*://%S+$") ~= nil
end

-- Minimal HTML->text reduction, good enough for the bare-URL check above
-- (not a general HTML renderer): drop tags, unescape the handful of
-- entities that could otherwise break the URL match.
local function strip_html_tags(html)
  local text = (html or ""):gsub("<[^>]->", "")
  text = text:gsub("&amp;", "&"):gsub("&lt;", "<"):gsub("&gt;", ">")
             :gsub("&quot;", '"'):gsub("&#39;", "'"):gsub("&nbsp;", " ")
  return text
end

-- sha256 of the sorted (uti=blob) set — the dedup key. Binary-safe.
local function type_hash(data_by_uti)
  local utis = {}
  local total = 0
  for uti, blob in pairs(data_by_uti) do
    utis[#utis + 1] = uti
    total = total + #(blob or "")
  end
  table.sort(utis)
  -- For very large single-image clips this still hashes the bytes; sha256
  -- is C-fast. The cap below skips oversized images before we get here.
  local parts = {}
  for _, uti in ipairs(utis) do
    parts[#parts + 1] = uti .. "=" .. (data_by_uti[uti] or "")
  end
  return hash.SHA256(table.concat(parts, "\n")), total
end

local PREVIEW_MAX_BYTES = 100

-- Truncate to at most `budget` bytes without splitting a UTF-8 sequence:
-- back off while the byte just past the cut is a continuation byte
-- (0x80-0xBF), which would mean the cut lands mid-codepoint. Hammerspoon
-- runs Lua 5.4 (which has `utf8`), but the spec harness runs 5.1 (which
-- does not), so this stays on plain byte arithmetic.
local function clip_bytes(s, budget)
  if #s <= budget then return s end
  local cut = budget
  while cut > 0 do
    local b = s:byte(cut + 1)
    if not b or b < 0x80 or b > 0xBF then break end
    cut = cut - 1
  end
  return s:sub(1, cut)
end

-- One-line snippet for the preview column: blank lines are dropped, every
-- other line is trimmed and joined with a single space.
--
-- This used to take only the text up to the first newline, which rendered a
-- clip that OPENS with a blank line as an empty row in the picker's list --
-- the whole snippet was the empty string before that first newline.
-- Flattening also puts more of a multi-line clip in the row, since the
-- budget is now spent on content rather than on whatever happened to sit on
-- line one. Pure -- see M._preview_of.
local function preview_of(text)
  if text == nil then return nil end
  local parts, len = {}, 0
  for line in text:gmatch("[^\r\n]+") do
    local trimmed = line:match("^%s*(.-)%s*$")
    if trimmed ~= "" then
      parts[#parts + 1] = trimmed
      -- +1 for the joining space. Stop once the budget is covered: a
      -- multi-megabyte clip must not be flattened in full to show 100 bytes.
      len = len + #trimmed + 1
      if len > PREVIEW_MAX_BYTES then break end
    end
  end
  local flat = table.concat(parts, " ")
  if #flat > PREVIEW_MAX_BYTES then
    return clip_bytes(flat, PREVIEW_MAX_BYTES) .. "…"
  end
  return flat
end
-- Not only a test seam: the picker calls this to re-derive a snippet for
-- rows stored before the flattening above existed (clipboard-picker.lua's
-- query_items).
M._preview_of = preview_of

-- Build the text_preview for a genuine multi-file "files" clip: full paths
-- newline-joined, staying inside preview_of()'s own ~100-char budget so the
-- column keeps its existing size discipline. Once the join would blow past
-- that, keep as many whole paths as fit and summarize the rest instead of
-- truncating mid-path. Pure -- test seam, see M._files_preview.
local function files_preview(paths)
  if not paths or #paths == 0 then return "[files]" end
  local joined = table.concat(paths, "\n")
  if #joined <= 100 then return joined end
  local out, len, shown = {}, 0, 0
  for _, p in ipairs(paths) do
    local candidate_len = len + #p + (shown > 0 and 1 or 0)
    if candidate_len > 100 then break end
    out[#out + 1] = p
    len = candidate_len
    shown = shown + 1
  end
  if shown == 0 then
    -- Not even the first path fits on its own -- show it truncated (mirrors
    -- preview_of()'s own truncation) rather than an all-summary preview
    -- with zero real content.
    return preview_of(paths[1]) .. "\n… +" .. (#paths - 1) .. " more"
  end
  local remaining = #paths - shown
  if remaining > 0 then
    return table.concat(out, "\n") .. "\n… +" .. remaining .. " more"
  end
  return table.concat(out, "\n")
end
M._files_preview = files_preview -- test seam only (pure function)

local function exec(sql)
  local rc = db:exec(sql)
  if rc ~= sqlite3.OK then
    hs.printf("clipboard-history: exec failed rc=%d: %s", rc or -1, sql)
  end
  return rc
end

-- True if `table_name` already has a column named `column_name`. SQLite has
-- no "ADD COLUMN IF NOT EXISTS", so migrations below check first.
local function column_exists(table_name, column_name)
  local st = db:prepare("PRAGMA table_info(" .. table_name .. ");")
  if not st then return false end
  local found = false
  while st:step() == sqlite3.ROW do
    if st:get_value(1) == column_name then found = true end
  end
  st:finalize()
  return found
end

local function ensure_schema()
  exec("PRAGMA journal_mode=WAL;")
  exec("PRAGMA synchronous=NORMAL;")
  -- Self-contained clips (spec §11): every clip a machine holds, it holds in
  -- full. `source_host` is the ONLY origin field (local iff it equals this
  -- machine's hostname). There is no `origin` column and no cross-machine
  -- reference id -- a clip is materialized in full wherever it is used.
  exec([[CREATE TABLE IF NOT EXISTS clips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text_preview TEXT,
    text_plain TEXT,
    len INTEGER,
    first_ts REAL,
    last_ts REAL,
    source_app TEXT,
    source_bundle_id TEXT,
    type_kind TEXT,
    regtype TEXT,
    pinned INTEGER DEFAULT 0,
    type_hash TEXT,
    source_host TEXT
  );]])
  exec([[CREATE TABLE IF NOT EXISTS clip_types (
    clip_id INTEGER,
    uti TEXT,
    blob BLOB,
    PRIMARY KEY (clip_id, uti)
  );]])
  exec("CREATE INDEX IF NOT EXISTS idx_clips_type_hash ON clips(type_hash);")
  exec("CREATE INDEX IF NOT EXISTS idx_clips_last_ts ON clips(last_ts DESC);")
  exec("CREATE INDEX IF NOT EXISTS idx_clips_pinned_ts ON clips(pinned DESC, last_ts DESC);")

  -- Migration for databases created before source_bundle_id existed (used
  -- for real app-icon lookup in the picker's metadata pane -- the app's
  -- display name alone isn't enough for hs.image.imageFromAppBundle).
  if not column_exists("clips", "source_bundle_id") then
    exec("ALTER TABLE clips ADD COLUMN source_bundle_id TEXT;")
  end

  -- source_host: the hostname where the clip was originally copied (§11).
  if not column_exists("clips", "source_host") then
    exec("ALTER TABLE clips ADD COLUMN source_host TEXT;")
  end

  -- Migration to the self-contained model (spec §11). Order matters:
  --   1. drop the old text-only mirror pointer rows (origin='remote-ref' /
  --      legacy 'laptop-ref') -- no blobs, cannot be made self-contained;
  --   2. backfill source_host on every remaining row (all pre-existing rows
  --      were local captures, so their origin is this machine);
  --   3. drop the now-dead `origin` and `ref_id` columns.
  if column_exists("clips", "origin") then
    exec("DELETE FROM clips WHERE origin IN ('remote-ref','laptop-ref');")
  end
  local host = (my_host() or ""):gsub("'", "''")
  exec("UPDATE clips SET source_host='" .. host ..
    "' WHERE source_host IS NULL OR source_host='';")
  if column_exists("clips", "origin") then
    exec("ALTER TABLE clips DROP COLUMN origin;")
  end
  if column_exists("clips", "ref_id") then
    exec("ALTER TABLE clips DROP COLUMN ref_id;")
  end
end

-- Drop oldest non-pinned rows until under both the row and byte caps.
local function enforce_retention()
  exec("DELETE FROM clips WHERE id IN ("
       .. " SELECT id FROM clips WHERE pinned=0 ORDER BY last_ts ASC "
       .. " LIMIT (SELECT MAX(0, COUNT(*) - " .. MAX_ROWS .. ") FROM clips)"
       .. ");")
  -- total-store byte cap: sum of clip_types.blob over the whole store.
  local st = assert(db:prepare(
    "SELECT (SELECT COUNT(*) FROM clips) AS n, "
    .. " (SELECT COALESCE(SUM(length(blob)),0) FROM clip_types) AS bytes;"))
  if st:step() == sqlite3.ROW then
    local n = st:get_value(0) or 0
    local bytes = st:get_value(1) or 0
    st:finalize()
    if bytes > MAX_STORE_BYTES then
      exec("DELETE FROM clips WHERE pinned=0 AND id IN ("
           .. " SELECT clip_id FROM clip_types GROUP BY clip_id "
           .. " ORDER BY (SELECT last_ts FROM clips c WHERE c.id=clip_id) ASC "
           .. " LIMIT " .. math.max(1, n - MAX_ROWS / 2)
           .. ");")
    end
  else
    st:finalize()
  end
  -- orphaned clip_types rows (cascade by hand: SQLite lacks FK enforcement
  -- unless PRAGMA foreign_keys=ON, which we don't rely on across processes).
  exec("DELETE FROM clip_types WHERE clip_id NOT IN (SELECT id FROM clips);")
end

-- Store one capture. Returns the clip id, or nil if skipped.
function M.capture_now()
  if not db then return nil end

  local types = pasteboard.allContentTypes() or {}
  local item_utis = types[1] or {}
  if #item_utis == 0 then return nil end

  -- Sensitive-type skip (spec §15): never store concealed/transient clips.
  for _, uti in ipairs(item_utis) do
    if SENSITIVE_UTIS[uti] then return nil end
  end

  -- App deny-list (spec §6).
  local app = hs.application.frontmostApplication()
  local app_name = app and app:name() or nil
  local app_bundle_id = app and app:bundleID() or nil
  if app_name and DENY_APPS[app_name] then return nil end

  -- Echo guard: when no interactive GUI user owns the session (frontmost is
  -- `loginwindow` / nil), a pasteboard change is not a genuine local copy but a
  -- bridge write echoing a *remote* machine's clip onto our pasteboard (e.g. a
  -- remote machine SSH'd in doing a T copy). Capturing it would stamp a clip
  -- that was really copied elsewhere with THIS machine's hostname (a bogus
  -- source_app='loginwindow', "local" row) — so skip it. The origin machine
  -- holds its own copy; if we use it here it materializes with ITS host (§11).
  if not app_name or app_name == "loginwindow" then return nil end

  local data_by_uti = pasteboard.readAllData() or {}
  if next(data_by_uti) == nil then return nil end

  local kind = classify(item_utis)
  local resolvedPath -- only set when kind refines to "file"/"directory" below
  local multi_paths  -- only set for a genuine multi-file "files" clip (>=2 real paths)

  if kind == "files" then
    local names = ns_filenames()
    if names and #names >= 2 then
      -- Genuine multi-file clip: stays "files" (ambiguous which of the N
      -- paths is a file vs a directory, so no file/directory refinement),
      -- but gets a real preview built from all N paths (see badge synth
      -- below) instead of the anonymous "[files]" badge.
      multi_paths = names
    else
      -- Exactly one path (or no parseable NSFilenamesPboardType at all --
      -- e.g. a non-Finder source that only sets public.file-url): refine
      -- to "file"/"directory" exactly as before.
      local refined, path = classify_file_or_directory()
      if refined then kind = refined; resolvedPath = path end
    end
  end

  -- Skip oversized images (spec §5: "skip images > ~5 MB").
  if kind == "image" or kind == "mixed" then
    for uti, blob in pairs(data_by_uti) do
      if uti:find("image", 1, true) and #(blob or "") > MAX_IMAGE_BYTES then
        return nil
      end
    end
  end

  local th, total_bytes = type_hash(data_by_uti)
  local plain = data_by_uti["public.utf8-plain-text"]
                or data_by_uti["public.text"]
                or data_by_uti["NSStringPboardType"]

  -- Empty-copy guard: a Cmd+C with nothing selected still bumps the pasteboard
  -- (the frontmost app places an empty public.utf8-plain-text on it), so the
  -- #item_utis and next(data_by_uti) guards above both pass — an empty blob
  -- value isn't nil. Without this, that blank copy lands a zero-length row at
  -- the top of history. Skip when the clip carries no real payload: for a
  -- text-bearing kind, nothing but whitespace; for any kind, zero total bytes.
  if kind == "text" or kind == "html" then
    if not plain or plain:match("^%s*$") then return nil end
  end
  if total_bytes == 0 then return nil end

  -- Reclassify a "just a URL, nothing else" text/html clip as "url" --
  -- checks the plain-text representation first, then (for html) falls
  -- back to the tag-stripped html, since either can carry the real text.
  if kind == "text" or kind == "html" then
    local isUrl = looks_like_bare_url(plain)
    if not isUrl and kind == "html" then
      isUrl = looks_like_bare_url(strip_html_tags(data_by_uti["public.html"]))
    end
    if isUrl then kind = "url" end
  end

  local preview = preview_of(plain)
  if not preview then
    -- non-text clip: synthesize a short badge from the kind + a payload hint
    if kind == "image" then preview = "[image]"
    elseif kind == "files" then preview = multi_paths and files_preview(multi_paths) or "[files]"
    -- Single file/directory: show the resolved path itself (same ~100-char
    -- right-truncate budget as any text preview via preview_of()), not the
    -- anonymous "[file]"/"[directory]" badge -- matches R5a's multi-file
    -- fix (files_preview) so the picker can glance-check what it's about to
    -- paste regardless of clip count.
    elseif kind == "file" then preview = resolvedPath and preview_of(resolvedPath) or "[file]"
    elseif kind == "directory" then preview = resolvedPath and preview_of(resolvedPath) or "[directory]"
    elseif kind == "rtf" then preview = "[rtf]"
    elseif kind == "html" then preview = "[html]"
    else preview = "[" .. kind .. "]" end
  end
  local len_val = plain and #plain or total_bytes
  if kind == "file" and resolvedPath then
    -- Real on-disk size, not the byte-length of the pasteboard's file-url
    -- string or the character count of the filename (what len_val would
    -- otherwise end up as for this kind).
    len_val = hs.fs.attributes(resolvedPath, "size") or len_val
  end
  if resolvedPath then
    -- Synthetic (non-pasteboard) UTI key, inserted below via the normal
    -- clip_types loop -- keeps the original public.file-url bytes intact
    -- (may matter for accurately restoring/pasting the clip later) while
    -- giving the picker a clean, human-readable path for its preview.
    data_by_uti["x-resolved-path"] = resolvedPath
  end
  local ts = now_ts()
  -- Record the register type if this clip was just set via the nvim bridge
  -- (its text hash matches the current-regtype file) — so a visual-block yank
  -- keeps its "b" in history and can be block-pasted later. nil otherwise.
  local cap_rt = captured_regtype(plain)
  local origin_host, suppress_echo = captured_origin(plain)
  if origin_host and suppress_echo then
    -- N-op echo suppression (see origin_file's contract note): the
    -- dispatcher already inserted the authoritative `files` manifest row for
    -- this very pasteboard change, so capturing its text echo here would add
    -- a duplicate, newer row that shadows the manifest. Consume the one-shot
    -- marker first -- only THIS capture is suppressed; a later identical
    -- copy declares no origin and captures normally -- then skip the insert
    -- entirely (same nil contract as the sensitive/deny-list skips above).
    os.remove(origin_file())
    return nil
  end

  -- Files-suppress (clipboard-mount spec §6): the dispatcher's M-op mount
  -- enrichment sets a file-urls pasteboard (mount-mapped paths) right after
  -- persisting the authoritative manifest row -- capturing that echo here
  -- would land a twin row (host=this Mac, mount paths) next to the manifest.
  -- A file-urls set carries no text UTI, so `plain` is nil and the text-hash
  -- suppress above can never match; rebuild the identity the dispatcher
  -- hashed instead: sha256 of the newline-joined captured paths (multi_paths
  -- for a >=2-path clip, the resolved single path otherwise -- same order as
  -- the NSFilenamesPboardType plist, which preserves the dispatcher's payload
  -- order). Same one-shot consume-the-marker semantics as the text suppress.
  if not origin_host and (kind == "files" or kind == "file" or kind == "directory") then
    local idpaths = multi_paths or (resolvedPath and { resolvedPath }) or nil
    if idpaths and #idpaths > 0 then
      local fhost, fsup = parse_origin_file(origin_file(),
        hash.SHA256(table.concat(idpaths, "\n")), now_ts())
      if fhost and fsup then
        os.remove(origin_file())
        return nil
      end
    end
  end
  local host = origin_host or my_host()

  -- Dedup on type_hash: bump last_ts + refresh source_app/preview if present.
  local dup = assert(db:prepare(
    "SELECT id FROM clips WHERE type_hash=? AND pinned=0 "
    .. " ORDER BY id DESC LIMIT 1;"))
  dup:bind(1, th)
  local existing_id
  if dup:step() == sqlite3.ROW then existing_id = dup:get_value(0) end
  dup:finalize()

  if existing_id then
    local up = assert(db:prepare(
      "UPDATE clips SET last_ts=?, source_app=?, source_bundle_id=?, text_preview=?, text_plain=?, "
      .. " len=?, type_kind=?, regtype=?, source_host=? WHERE id=?;"))
    up:bind(1, ts); up:bind(2, app_name); up:bind(3, app_bundle_id); up:bind(4, preview); up:bind(5, plain)
    up:bind(6, len_val); up:bind(7, kind); up:bind(8, cap_rt); up:bind(9, host); up:bind(10, existing_id)
    up:step(); up:finalize()
    enforce_retention()
    return existing_id
  end

  -- New row.
  local ins = assert(db:prepare(
    "INSERT INTO clips (text_preview, text_plain, len, first_ts, last_ts, "
    .. " source_app, source_bundle_id, type_kind, regtype, pinned, type_hash, source_host) "
    .. " VALUES (?,?,?,?,?,?,?,?,  ?, 0, ?, ?);"))
  ins:bind(1, preview); ins:bind(2, plain); ins:bind(3, len_val)
  ins:bind(4, ts); ins:bind(5, ts); ins:bind(6, app_name); ins:bind(7, app_bundle_id)
  ins:bind(8, kind); ins:bind(9, cap_rt); ins:bind(10, th); ins:bind(11, host)
  ins:step(); ins:finalize()
  local new_id = db:last_insert_rowid()

  -- Rich payloads: one clip_types row per UTI.
  for uti, blob in pairs(data_by_uti) do
    if blob ~= nil then
      local ct = assert(db:prepare(
        "INSERT OR REPLACE INTO clip_types (clip_id, uti, blob) VALUES (?,?,?);"))
      ct:bind(1, new_id); ct:bind(2, uti); ct:bind_blob(3, blob)
      ct:step(); ct:finalize()
    end
  end

  enforce_retention()
  return new_id
end

-- Watcher callback: ignore the string arg (nil for non-text clips) and do
-- our own full read. Guard against re-processing the same changeCount.
local function on_change(_v)
  local cc = pasteboard.changeCount()
  if cc == last_change then return end
  last_change = cc
  M.capture_now()
end

function M.setup()
  if db then return end
  os.execute("mkdir -p " .. (data_dir() .. "/pick-clipboard"):gsub("'", [["'"]]))
  db = sqlite3.open(db_path())
  if type(db) ~= "userdata" then
    hs.printf("clipboard-history: could not open %s", db_path())
    db = nil
    return
  end
  ensure_schema()
  last_change = pasteboard.changeCount()
  pasteboard.watcher.interval(0.5)
  watcher = pasteboard.watcher.new(on_change)
  -- `new` starts the watcher already; nothing else to do.
end

function M.cleanup()
  if watcher then watcher:stop(); watcher = nil end
  if db then db:close(); db = nil end
end

-- Test/inspection helpers (not used in production paths).
function M._db_path() return db_path() end
-- This machine's hostname, as stamped into source_host on local captures. The
-- GUI picker compares it against each row's source_host to badge remote clips.
function M._my_host() return my_host() end
function M._row_count()
  if not db then return nil end
  local s = assert(db:prepare("SELECT COUNT(*) FROM clips;"))
  local n
  if s:step() == sqlite3.ROW then n = s:get_value(0) end
  s:finalize()
  return n
end

--------------------------------------------------------------------------------
-- GUI picker support: restore-by-id (spec §10)
--------------------------------------------------------------------------------
-- The Cmd+Shift+V picker UI itself lives in apps/clipboard-picker.lua (a
-- custom hs.webview matching the WhichKey visual identity — hs.chooser can't
-- do split panes, custom styling, or bind Ctrl-D/Ctrl-P/Alt-Enter). This
-- module keeps only the DB-facing restore primitive both the picker and any
-- future consumer need.

local function bump_last_ts(id)
  local b = db:prepare("UPDATE clips SET last_ts=? WHERE id=?;")
  if b then b:bind(1, now_ts()); b:bind(2, id); b:step(); b:finalize() end
end

local function fetch_clip_types(id)
  local s = assert(db:prepare("SELECT uti, blob FROM clip_types WHERE clip_id=?;"))
  s:bind(1, id)
  local data = {}
  while s:step() == sqlite3.ROW do
    data[s:get_value(0)] = s:get_value(1)  -- uti -> blob (Lua string)
  end
  s:finalize()
  return data
end

local function fetch_text_plain(id)
  local t = assert(db:prepare("SELECT text_plain FROM clips WHERE id=?;"))
  t:bind(1, id)
  local plain
  if t:step() == sqlite3.ROW then plain = t:get_value(0) end
  t:finalize()
  return plain
end

-- Restore a clip's full rich pasteboard by id (all UTI->blob rows from
-- clip_types). Returns true on success. Also bumps last_ts (spec §10
-- "re-bump last_ts on pick"). The pasteboard write bumps changeCount, so the
-- watcher will re-observe it (dedup bumps the same row again — harmless).
function M.restore_by_id(id)
  if not db or not id then return false end
  local data = fetch_clip_types(id)
  if next(data) == nil then
    -- No rich payload (e.g. a materialized text-only row): fall back to text_plain.
    local plain = fetch_text_plain(id)
    if not plain then return false end
    pasteboard.setContents(plain)
  else
    pasteboard.writeAllData(data)
  end
  write_regtype_for(id) -- reinstate the register type so a later nvim paste keeps block-ness
  bump_last_ts(id)
  return true
end

-- POSIX path -> a valid file:// URI, percent-encoding each path segment
-- individually (not the whole string at once, which would also escape the
-- "/" separators themselves).
local function path_to_file_url(path)
  local segments = {}
  for seg in path:gmatch("[^/]+") do
    segments[#segments + 1] = hs.http.encodeForQuery(seg)
  end
  return "file:///" .. table.concat(segments, "/")
end

local function basename(path)
  return path:match("([^/]+)/?$") or path
end

-- Same UTI/MIME set as IMAGE_UTIS/IMAGE_MIME in clipboard-picker.lua --
-- duplicated rather than shared: this module is the lower-level one (the
-- picker already requires it), so it can't require the picker back
-- without a cycle, and it's a handful of lines, not worth a new shared
-- module for.
local IMAGE_UTIS = { "public.png", "public.jpeg", "public.tiff", "com.compuserve.gif" }
local IMAGE_MIME = {
  ["public.png"] = "image/png", ["public.jpeg"] = "image/jpeg",
  ["public.tiff"] = "image/tiff", ["com.compuserve.gif"] = "image/gif",
}

-- [label](target) markdown link/image for file/directory/url/image clips
-- (spec: Alt+Enter). Returns nil if there's nothing to link to (shouldn't
-- happen for these kinds in practice, but restore_plain_by_id below falls
-- back to its normal text_plain path if so).
local function markdown_link_for(id, kind)
  if kind == "url" then
    local url = fetch_text_plain(id)
    if not url or url == "" then return nil end
    return "[" .. url .. "](" .. url .. ")"
  end
  if kind == "image" then
    for _, uti in ipairs(IMAGE_UTIS) do
      local s = db:prepare("SELECT blob FROM clip_types WHERE clip_id=? AND uti=?;")
      s:bind(1, id); s:bind(2, uti)
      local blob
      if s:step() == sqlite3.ROW then blob = s:get_value(0) end
      s:finalize()
      if blob then
        local ok, b64 = pcall(hs.base64.encode, blob)
        if ok and b64 then
          return "![](data:" .. (IMAGE_MIME[uti] or "image/png") .. ";base64," .. b64 .. ")"
        end
      end
    end
    return nil
  end
  local s = assert(db:prepare("SELECT blob FROM clip_types WHERE clip_id=? AND uti='x-resolved-path';"))
  s:bind(1, id)
  local path
  if s:step() == sqlite3.ROW then path = s:get_value(0) end
  s:finalize()
  if not path then return nil end
  return "[" .. basename(path) .. "](" .. path_to_file_url(path) .. ")"
end

-- Restore ONLY the plain-text representation of a clip -- RTF/HTML styling
-- stripped, file/directory/url clips linkified as markdown (spec:
-- Alt+Enter). text_plain already covers the vast majority of real
-- captures (macOS copy operations from rich sources almost always also
-- place a plain-text sibling on the pasteboard); when it's genuinely
-- missing, derive it from whatever rich payload IS available via
-- hs.styledtext's own text conversion rather than failing outright.
function M.restore_plain_by_id(id)
  if not db or not id then return false end

  local k = assert(db:prepare("SELECT type_kind FROM clips WHERE id=?;"))
  k:bind(1, id)
  local kind
  if k:step() == sqlite3.ROW then kind = k:get_value(0) end
  k:finalize()

  if kind == "file" or kind == "directory" or kind == "url" or kind == "image" then
    local link = markdown_link_for(id, kind)
    if link then
      pasteboard.setContents(link)
      bump_last_ts(id)
      return true
    end
  end

  local plain = fetch_text_plain(id)
  if not plain or plain == "" then
    local data = fetch_clip_types(id)
    local html = data["public.html"]
    local rtf = data["public.rtf"]
    local rtfd = data["NeXT RTFD pasteboard type"] or data["Apple RTFD pasteboard type"]
    local ok, st
    if html then ok, st = pcall(hs.styledtext.getStyledTextFromData, html, "html")
    elseif rtf then ok, st = pcall(hs.styledtext.getStyledTextFromData, rtf, "rtf")
    elseif rtfd then ok, st = pcall(hs.styledtext.getStyledTextFromData, rtfd, "rtfd")
    end
    if ok and st then
      local ok2, text = pcall(function() return st:convert("text") end)
      if ok2 and text then plain = text end
    end
  end
  if not plain or plain == "" then return false end
  pasteboard.setContents(plain)
  bump_last_ts(id)
  return true
end

return M
