//! The capture pipeline — §14.2's behaviors, absorbed from the watcher.
//!
//! Every rule here is a port of `clipboard-history.lua`'s capture path, and
//! §14.2 makes each one a requirement with a test rather than an implementation
//! note: the sensitive-UTI refusal, the password-manager deny-list, the empty
//! and whitespace-only rejection, the 5 MB image cap, classification, and the
//! `type_hash` dedup key. The risk this module manages is the one §6.2 names —
//! "the rewrite quietly dropped the password-manager guard" is precisely the
//! kind of regression a wire-protocol document is bad at noticing — so the port
//! is deliberately literal, down to evaluation order.
//!
//! Nothing here touches a pasteboard. The macOS platform layer builds a
//! [`Snapshot`] from the real one and the store writes the resulting
//! [`Capture`]; this module is the decision between them, and it compiles and
//! is tested on Linux, which is what keeps the reduced build honest (§14.7).

use std::collections::BTreeMap;

use sha2::{Digest, Sha256};

/// §14.2: never capture concealed/transient/auto-generated pasteboards, nor the
/// private marker the mount enrichment stamps on peer-derived file URLs — those
/// paths came from an unauthenticated peer pointer and must never become local
/// file authority (`clipboard-history.lua:45-53`).
const SENSITIVE_UTIS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "org.chezmoi.clipboard.UntrustedFileURLs",
];

/// §14.2: refuse to capture while a password manager is frontmost. A security
/// control, not a convenience — Q7 was probed before §14 could be written
/// because losing this silently was the failure being guarded against.
const DENY_APPS: &[&str] = &[
    "Keychain Access",
    "1Password",
    "1Password 7",
    "1Password 8",
    "Bitwarden",
    "Dashlane",
    "KeePassXC",
];

/// §14.2: skip any image representation above 5 MB.
const MAX_IMAGE_BYTES: usize = 5 * 1024 * 1024;

/// The preview column's byte budget (`clipboard-history.lua:310`).
const PREVIEW_MAX_BYTES: usize = 100;

/// Lua's `%s` class: space, tab, LF, VT, FF, CR. Rust's `char::is_whitespace`
/// covers Unicode spaces and would trim more than the Lua trims, so the port
/// names the set explicitly.
const LUA_WS: &[char] = &[' ', '\t', '\n', '\x0b', '\x0c', '\r'];

/// The frontmost application at capture time, from the platform layer.
#[derive(Clone, Debug)]
pub struct FrontmostApp {
    pub name: String,
    pub bundle_id: Option<String>,
}

/// One observed pasteboard state, read atomically enough for the pipeline to
/// judge. The platform layer resolves everything that needs AppKit — the type
/// list, the blobs, the frontmost application, the parsed
/// `NSFilenamesPboardType` plist and the `readURL().filePath` equivalent — so
/// the decision itself stays platform-neutral and Linux-testable.
#[derive(Clone, Debug, Default)]
pub struct Snapshot {
    /// The first pasteboard item's declared types, in pasteboard order
    /// (`allContentTypes()[1]` in the Lua).
    pub item_utis: Vec<String>,
    /// UTI → payload (`readAllData()` in the Lua). A `BTreeMap` because
    /// `type_hash` needs the sorted order anyway.
    pub data: BTreeMap<String, Vec<u8>>,
    pub frontmost: Option<FrontmostApp>,
    /// The parsed `NSFilenamesPboardType` property list, when present. Read by
    /// legacy type *name*, not enumerated UTI — a restored clip re-advertises
    /// the blob under a dynamic `dyn.*` UTI and only name-based bridging still
    /// resolves it (`clipboard-history.lua:250-272`, verified live in R5a).
    pub filenames: Option<Vec<String>>,
    /// `readURL().filePath` equivalent: the first item's file URL resolved to a
    /// real path, including the opaque `file:///.file/id=…` reference form.
    pub resolved_url_path: Option<String>,
}

/// Why a pasteboard change was not captured. Every variant is a deliberate
/// refusal from `clipboard-history.lua`'s capture path, in its evaluation
/// order.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Skip {
    /// No declared types at all.
    NoTypes,
    /// A sensitive UTI was present (§14.2).
    SensitiveUti,
    /// The frontmost application is on the password-manager deny-list (§14.2).
    DeniedApp,
    /// No interactive GUI user owns the session (frontmost nil or
    /// `loginwindow`): the change is a bridge write echoing a remote machine's
    /// clip, and capturing it would stamp it as a local copy
    /// (`clipboard-history.lua:583-590`).
    NoGuiSession,
    /// Declared types but no readable payload.
    NoData,
    /// An image representation above the 5 MB cap (§14.2).
    OversizedImage,
    /// A text-bearing kind with nothing but whitespace (§14.2).
    WhitespaceOnly,
    /// Zero payload bytes in total (§14.2's empty rejection).
    NoPayload,
}

/// The store row's `type_kind` column (§14.2 classification).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TypeKind {
    Text,
    Rtf,
    Html,
    Image,
    Files,
    File,
    Directory,
    Mixed,
    Url,
}

impl TypeKind {
    pub fn as_str(self) -> &'static str {
        match self {
            TypeKind::Text => "text",
            TypeKind::Rtf => "rtf",
            TypeKind::Html => "html",
            TypeKind::Image => "image",
            TypeKind::Files => "files",
            TypeKind::File => "file",
            TypeKind::Directory => "directory",
            TypeKind::Mixed => "mixed",
            TypeKind::Url => "url",
        }
    }
}

/// A capture the store should write: the row fields plus the `clip_types`
/// payload set (including the synthetic `x-resolved-path` entry the picker
/// previews) and the exact local paths the row may expose as file authority.
#[derive(Debug, PartialEq)]
pub struct Capture {
    pub kind: TypeKind,
    pub type_hash: String,
    pub plain: Option<String>,
    pub preview: String,
    pub len: i64,
    pub source_app: Option<String>,
    pub source_bundle_id: Option<String>,
    /// UTI → payload, with `x-resolved-path` appended when a single-path file
    /// clip resolved. Excluded from `type_hash`, which was computed first —
    /// same order as the Lua, and load-bearing for dedup.
    pub data: BTreeMap<String, Vec<u8>>,
    pub authority_paths: Option<Vec<String>>,
}

/// The §14.2 capture decision, ported from `clipboard-history.lua`'s
/// `capture_now` with the same checks in the same order. `regtype` is not an
/// input: an *observed* change is by definition not one of the daemon's own
/// writes (those are filtered by `changeCount` before this runs, §6.2), so the
/// row's register type is unknown — the sidecar file the Lua consulted is
/// deleted by §14.6.
pub fn decide(snap: &Snapshot) -> Result<Capture, Skip> {
    if snap.item_utis.is_empty() {
        return Err(Skip::NoTypes);
    }
    for uti in &snap.item_utis {
        if SENSITIVE_UTIS.contains(&uti.as_str()) {
            return Err(Skip::SensitiveUti);
        }
    }

    let app_name = snap.frontmost.as_ref().map(|app| app.name.as_str());
    if let Some(name) = app_name {
        if DENY_APPS.contains(&name) {
            return Err(Skip::DeniedApp);
        }
    }
    // Echo guard: when no interactive GUI user owns the session, a pasteboard
    // change is a bridge write echoing a remote machine's clip, not a local
    // copy. The origin machine holds its own row.
    match app_name {
        None | Some("loginwindow") => return Err(Skip::NoGuiSession),
        Some(_) => {}
    }

    if snap.data.is_empty() {
        return Err(Skip::NoData);
    }

    let mut kind = classify(&snap.item_utis);
    let mut resolved_path: Option<String> = None;
    let mut multi_paths: Option<&[String]> = None;
    let mut authority_paths: Option<Vec<String>> = None;

    if kind == TypeKind::Files {
        match snap.filenames.as_deref() {
            Some(names) if names.len() >= 2 => {
                // A genuine multi-file clip stays "files" — it is ambiguous
                // which of the N paths is a file versus a directory — but gets
                // a real preview from all N paths instead of the anonymous
                // badge.
                multi_paths = Some(names);
                authority_paths = Some(names.to_vec());
            }
            names => {
                // Exactly one path, or no parseable NSFilenamesPboardType at
                // all: refine to file/directory from the resolved URL path.
                if let Some((refined, path)) = classify_file_or_directory(snap) {
                    kind = refined;
                    authority_paths = Some(vec![path.clone()]);
                    resolved_path = Some(path);
                } else if let Some(names) = names.filter(|n| n.len() == 1) {
                    // Keep a parseable standard file-list path authoritative
                    // even when the file-versus-directory kind could not be
                    // refined.
                    authority_paths = Some(names.to_vec());
                }
            }
        }
    }

    if kind == TypeKind::Image || kind == TypeKind::Mixed {
        for (uti, blob) in &snap.data {
            if is_image_uti(uti) && blob.len() > MAX_IMAGE_BYTES {
                return Err(Skip::OversizedImage);
            }
        }
    }

    // The dedup key, over the payload set as observed — before the synthetic
    // `x-resolved-path` entry is added below, exactly as the Lua orders it.
    let (type_hash, total_bytes) = type_hash(&snap.data);
    let plain = [
        "public.utf8-plain-text",
        "public.text",
        "NSStringPboardType",
    ]
    .iter()
    .find_map(|uti| snap.data.get(*uti))
    .map(|blob| String::from_utf8_lossy(blob).into_owned());

    // Empty-copy guard: a Cmd+C with nothing selected still bumps the
    // pasteboard with an empty plain-text payload, which passes both presence
    // checks above.
    if kind == TypeKind::Text || kind == TypeKind::Html {
        match &plain {
            Some(text) if !text.trim_matches(LUA_WS).is_empty() => {}
            _ => return Err(Skip::WhitespaceOnly),
        }
    }
    if total_bytes == 0 {
        return Err(Skip::NoPayload);
    }

    // Reclassify a "just a URL, nothing else" text/html clip as `url`.
    if kind == TypeKind::Text || kind == TypeKind::Html {
        let mut is_url = plain.as_deref().is_some_and(looks_like_bare_url);
        if !is_url && kind == TypeKind::Html {
            if let Some(html) = snap.data.get("public.html") {
                is_url = looks_like_bare_url(&strip_html_tags(&String::from_utf8_lossy(html)));
            }
        }
        if is_url {
            kind = TypeKind::Url;
        }
    }

    // The Lua synthesizes a badge only when `plain` is nil — an empty string is
    // truthy there and stays an empty preview. Port that, not an improvement.
    let preview = match &plain {
        Some(text) => preview_of(text),
        None => match kind {
            TypeKind::Image => "[image]".to_string(),
            TypeKind::Files => multi_paths.map_or_else(|| "[files]".to_string(), files_preview),
            TypeKind::File => resolved_path
                .as_deref()
                .map_or_else(|| "[file]".to_string(), preview_of),
            TypeKind::Directory => resolved_path
                .as_deref()
                .map_or_else(|| "[directory]".to_string(), preview_of),
            other => format!("[{}]", other.as_str()),
        },
    };

    let mut len = plain.as_ref().map_or(total_bytes, String::len) as i64;
    if kind == TypeKind::File {
        if let Some(path) = &resolved_path {
            // The real on-disk size, not the byte length of the file-url
            // string or of the filename.
            if let Ok(meta) = std::fs::metadata(path) {
                len = meta.len() as i64;
            }
        }
    }

    let mut data = snap.data.clone();
    if let Some(path) = &resolved_path {
        // Synthetic (non-pasteboard) UTI: keeps the original public.file-url
        // bytes intact for restore while giving the picker a clean path for
        // its preview.
        data.insert("x-resolved-path".to_string(), path.clone().into_bytes());
    }

    Ok(Capture {
        kind,
        type_hash,
        plain,
        preview,
        len,
        source_app: snap.frontmost.as_ref().map(|app| app.name.clone()),
        source_bundle_id: snap
            .frontmost
            .as_ref()
            .and_then(|app| app.bundle_id.clone()),
        data,
        authority_paths,
    })
}

/// §14.2 classification from the UTI set: rich kinds are counted in a fixed
/// order — 0 means `text`, exactly 1 means that kind, more means `mixed`.
fn classify(utis: &[String]) -> TypeKind {
    let has = |name: &str| utis.iter().any(|uti| uti == name);
    let mut rich = Vec::new();
    if has("public.rtf") || has("NeXT RTFD pasteboard type") || has("Apple RTFD") {
        rich.push(TypeKind::Rtf);
    }
    if has("public.html") {
        rich.push(TypeKind::Html);
    }
    if has("public.png")
        || has("public.jpeg")
        || has("public.tiff")
        || has("com.compuserve.gif")
        || has("public.image")
    {
        rich.push(TypeKind::Image);
    }
    if has("public.file-url") || has("NSFilenamesPboardType") {
        rich.push(TypeKind::Files);
    }
    match rich.as_slice() {
        [] => TypeKind::Text,
        [one] => *one,
        _ => TypeKind::Mixed,
    }
}

/// An image representation, for the §14.2 size cap: the concrete image UTIs
/// `classify` recognizes, plus anything naming "image" outright.
///
/// Deliberately wider than the Lua's literal `uti:find("image")`, which never
/// matches `public.png`, `public.jpeg` or `public.tiff` — under that test a
/// 6 MB PNG sails past the cap the comment above it claims. §14.2 requires
/// "skip any image representation above 5 MB", and the spec outranks the
/// accident (reported with Phase 3, not patched silently: this makes the
/// daemon enforce what the Lua only intended).
fn is_image_uti(uti: &str) -> bool {
    matches!(
        uti,
        "public.png" | "public.jpeg" | "public.tiff" | "com.compuserve.gif"
    ) || uti.contains("image")
}

/// The single-path refinement: stat the resolved URL path and split
/// file-versus-directory. `None` keeps the generic `files` kind, exactly as
/// the Lua does when resolution or the stat fails.
fn classify_file_or_directory(snap: &Snapshot) -> Option<(TypeKind, String)> {
    let path = snap.resolved_url_path.as_ref()?;
    let meta = std::fs::metadata(path).ok()?;
    if meta.is_dir() {
        Some((TypeKind::Directory, path.clone()))
    } else if meta.is_file() {
        Some((TypeKind::File, path.clone()))
    } else {
        None
    }
}

/// §14.2's dedup key: SHA-256 over the sorted `uti=blob` set joined by
/// newlines, hex-encoded — byte-identical to `hs.hash.SHA256` over the same
/// construction, which is what lets a daemon capture dedup against a row the
/// Lua writer inserted during the Phase 3–7 window. Also returns the total
/// payload size, summed in the same pass as the Lua does.
pub fn type_hash(data: &BTreeMap<String, Vec<u8>>) -> (String, usize) {
    let mut hasher = Sha256::new();
    let mut total = 0;
    for (index, (uti, blob)) in data.iter().enumerate() {
        if index > 0 {
            hasher.update(b"\n");
        }
        hasher.update(uti.as_bytes());
        hasher.update(b"=");
        hasher.update(blob);
        total += blob.len();
    }
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(64);
    for byte in digest {
        use std::fmt::Write;
        let _ = write!(hex, "{byte:02x}");
    }
    (hex, total)
}

/// Truncate to at most `budget` bytes without splitting a UTF-8 sequence.
fn clip_bytes(s: &str, budget: usize) -> &str {
    if s.len() <= budget {
        return s;
    }
    let mut cut = budget;
    while cut > 0 && !s.is_char_boundary(cut) {
        cut -= 1;
    }
    &s[..cut]
}

/// One-line snippet for the preview column: blank lines dropped, every other
/// line trimmed and joined with a single space, cut at the byte budget with an
/// ellipsis. The flattening exists because a clip that *opens* with a blank
/// line used to render as an empty picker row (`clipboard-history.lua:337`).
fn preview_of(text: &str) -> String {
    let mut parts: Vec<&str> = Vec::new();
    let mut len = 0;
    for line in text.split(['\r', '\n']) {
        let trimmed = line.trim_matches(LUA_WS);
        if !trimmed.is_empty() {
            parts.push(trimmed);
            // +1 for the joining space. Stop once the budget is covered: a
            // multi-megabyte clip must not be flattened in full to show 100
            // bytes.
            len += trimmed.len() + 1;
            if len > PREVIEW_MAX_BYTES {
                break;
            }
        }
    }
    let flat = parts.join(" ");
    if flat.len() > PREVIEW_MAX_BYTES {
        format!("{}…", clip_bytes(&flat, PREVIEW_MAX_BYTES))
    } else {
        flat
    }
}

/// The preview for a genuine multi-file clip: full paths newline-joined inside
/// the same byte budget, keeping whole paths and summarizing the rest rather
/// than truncating mid-path (`clipboard-history.lua:366`).
fn files_preview(paths: &[String]) -> String {
    if paths.is_empty() {
        return "[files]".to_string();
    }
    let joined = paths.join("\n");
    if joined.len() <= PREVIEW_MAX_BYTES {
        return joined;
    }
    let mut out: Vec<&str> = Vec::new();
    let mut len = 0;
    for path in paths {
        let candidate = len + path.len() + usize::from(!out.is_empty());
        if candidate > PREVIEW_MAX_BYTES {
            break;
        }
        out.push(path);
        len = candidate;
    }
    if out.is_empty() {
        // Not even the first path fits on its own — show it truncated rather
        // than an all-summary preview with zero real content.
        return format!("{}\n… +{} more", preview_of(&paths[0]), paths.len() - 1);
    }
    let remaining = paths.len() - out.len();
    if remaining > 0 {
        format!("{}\n… +{remaining} more", out.join("\n"))
    } else {
        out.join("\n")
    }
}

/// Best-effort "is this JUST a URL, with nothing else": trimmed and anchored
/// end to end — `scheme://` then no whitespace, nothing besides that.
fn looks_like_bare_url(s: &str) -> bool {
    let s = s.trim_matches(LUA_WS);
    let Some(sep) = s.find("://") else {
        return false;
    };
    let (scheme, rest) = (&s[..sep], &s[sep + 3..]);
    let mut chars = scheme.chars();
    if !chars.next().is_some_and(|c| c.is_ascii_alphabetic()) {
        return false;
    }
    if !chars.all(|c| c.is_ascii_alphanumeric() || matches!(c, '+' | '.' | '-')) {
        return false;
    }
    !rest.is_empty() && !rest.contains(LUA_WS)
}

/// Minimal HTML→text reduction, good enough for the bare-URL check above and
/// nothing more: drop tags, unescape the handful of entities that could break
/// the URL match — `&amp;` first, in the Lua's replacement order.
fn strip_html_tags(html: &str) -> String {
    let mut text = String::with_capacity(html.len());
    let mut rest = html;
    while let Some(open) = rest.find('<') {
        text.push_str(&rest[..open]);
        match rest[open..].find('>') {
            Some(close) => rest = &rest[open + close + 1..],
            None => {
                // No closing bracket: the Lua pattern leaves the tail as-is.
                text.push_str(&rest[open..]);
                rest = "";
            }
        }
    }
    text.push_str(rest);
    text.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        .replace("&nbsp;", " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn text_snapshot(text: &str) -> Snapshot {
        let mut data = BTreeMap::new();
        data.insert(
            "public.utf8-plain-text".to_string(),
            text.as_bytes().to_vec(),
        );
        Snapshot {
            item_utis: vec!["public.utf8-plain-text".to_string()],
            data,
            frontmost: Some(FrontmostApp {
                name: "Ghostty".to_string(),
                bundle_id: Some("com.mitchellh.ghostty".to_string()),
            }),
            filenames: None,
            resolved_url_path: None,
        }
    }

    #[test]
    fn a_plain_text_copy_is_captured_with_attribution() {
        let capture = decide(&text_snapshot("hello world")).expect("captured");
        assert_eq!(capture.kind, TypeKind::Text);
        assert_eq!(capture.plain.as_deref(), Some("hello world"));
        assert_eq!(capture.preview, "hello world");
        assert_eq!(capture.len, 11);
        assert_eq!(capture.source_app.as_deref(), Some("Ghostty"));
        assert_eq!(
            capture.source_bundle_id.as_deref(),
            Some("com.mitchellh.ghostty")
        );
    }

    #[test]
    fn every_sensitive_uti_refuses_capture() {
        for uti in SENSITIVE_UTIS {
            let mut snap = text_snapshot("secret");
            snap.item_utis.push((*uti).to_string());
            assert_eq!(decide(&snap), Err(Skip::SensitiveUti), "uti {uti}");
        }
    }

    #[test]
    fn every_password_manager_on_the_deny_list_refuses_capture() {
        // §14.2 calls this a security control: the rewrite silently dropping it
        // is the named failure mode of absorbing the watcher.
        for app in DENY_APPS {
            let mut snap = text_snapshot("hunter2");
            snap.frontmost = Some(FrontmostApp {
                name: (*app).to_string(),
                bundle_id: None,
            });
            assert_eq!(decide(&snap), Err(Skip::DeniedApp), "app {app}");
        }
    }

    #[test]
    fn no_gui_session_refuses_capture() {
        let mut snap = text_snapshot("echoed remote clip");
        snap.frontmost = None;
        assert_eq!(decide(&snap), Err(Skip::NoGuiSession));
        snap.frontmost = Some(FrontmostApp {
            name: "loginwindow".to_string(),
            bundle_id: None,
        });
        assert_eq!(decide(&snap), Err(Skip::NoGuiSession));
    }

    #[test]
    fn empty_and_whitespace_only_text_is_refused() {
        assert_eq!(decide(&text_snapshot("")), Err(Skip::WhitespaceOnly));
        assert_eq!(
            decide(&text_snapshot("  \t\n  ")),
            Err(Skip::WhitespaceOnly)
        );
        let mut snap = Snapshot {
            item_utis: vec!["public.utf8-plain-text".to_string()],
            ..text_snapshot("x")
        };
        snap.data.clear();
        assert_eq!(decide(&snap), Err(Skip::NoData));
        assert_eq!(decide(&Snapshot::default()), Err(Skip::NoTypes));
    }

    #[test]
    fn an_image_above_the_cap_is_refused_and_one_below_is_kept() {
        let mut snap = text_snapshot("ignored");
        snap.item_utis = vec!["public.png".to_string()];
        snap.data.clear();
        snap.data
            .insert("public.png".to_string(), vec![0u8; MAX_IMAGE_BYTES + 1]);
        assert_eq!(decide(&snap), Err(Skip::OversizedImage));

        snap.data.insert("public.png".to_string(), vec![0u8; 1024]);
        let capture = decide(&snap).expect("captured");
        assert_eq!(capture.kind, TypeKind::Image);
        assert_eq!(capture.preview, "[image]");
        assert_eq!(capture.len, 1024, "len falls back to total payload bytes");
    }

    #[test]
    fn classification_covers_every_kind() {
        let one = |uti: &str| vec![uti.to_string()];
        assert_eq!(classify(&one("public.utf8-plain-text")), TypeKind::Text);
        assert_eq!(classify(&one("public.rtf")), TypeKind::Rtf);
        assert_eq!(classify(&one("public.html")), TypeKind::Html);
        assert_eq!(classify(&one("public.jpeg")), TypeKind::Image);
        assert_eq!(classify(&one("public.file-url")), TypeKind::Files);
        assert_eq!(classify(&one("NSFilenamesPboardType")), TypeKind::Files);
        assert_eq!(
            classify(&["public.rtf".to_string(), "public.html".to_string()]),
            TypeKind::Mixed
        );
    }

    #[test]
    fn a_bare_url_reclassifies_and_prose_does_not() {
        let capture = decide(&text_snapshot("  https://example.com/x?q=1  ")).expect("captured");
        assert_eq!(capture.kind, TypeKind::Url);
        let capture = decide(&text_snapshot("see https://example.com")).expect("captured");
        assert_eq!(capture.kind, TypeKind::Text);
    }

    #[test]
    fn an_html_only_bare_url_reclassifies_through_tag_stripping() {
        // The plain sibling is not itself a URL, so only the tag-stripped HTML
        // fallback can reclassify this one.
        let html = b"<a>https://example.com</a>";
        let mut snap = Snapshot {
            item_utis: vec!["public.html".to_string()],
            ..Default::default()
        };
        snap.data.insert("public.html".to_string(), html.to_vec());
        snap.data
            .insert("public.utf8-plain-text".to_string(), b"click here".to_vec());
        snap.frontmost = text_snapshot("x").frontmost;
        assert_eq!(decide(&snap).expect("captured").kind, TypeKind::Url);
    }

    #[test]
    fn the_type_hash_matches_the_lua_construction() {
        // sha256("a=1\nb=2"), the sorted uti=blob set joined by newlines —
        // computed independently to pin the byte layout, since dedup against
        // rows the Lua writer inserted depends on it.
        let mut data = BTreeMap::new();
        data.insert("b".to_string(), b"2".to_vec());
        data.insert("a".to_string(), b"1".to_vec());
        let (hash, total) = type_hash(&data);
        let mut hasher = Sha256::new();
        hasher.update(b"a=1\nb=2");
        let expected: Vec<String> = hasher
            .finalize()
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect();
        assert_eq!(hash, expected.concat());
        assert_eq!(total, 2);
    }

    #[test]
    fn the_hash_is_computed_before_the_synthetic_resolved_path_entry() {
        let dir = crate::testutil::tempdir("capture-file");
        let path = dir.path().join("clip.txt");
        std::fs::write(&path, b"12345").unwrap();
        let url_blob = format!("file://{}", path.display()).into_bytes();

        let mut snap = Snapshot {
            item_utis: vec!["public.file-url".to_string()],
            ..Default::default()
        };
        snap.data.insert("public.file-url".to_string(), url_blob);
        snap.frontmost = text_snapshot("x").frontmost;
        snap.resolved_url_path = Some(path.to_string_lossy().into_owned());

        let (expected_hash, _) = type_hash(&snap.data);
        let capture = decide(&snap).expect("captured");
        assert_eq!(capture.kind, TypeKind::File);
        assert_eq!(
            capture.type_hash, expected_hash,
            "hash excludes the synthetic entry"
        );
        assert!(capture.data.contains_key("x-resolved-path"));
        assert_eq!(capture.len, 5, "len is the on-disk size for a file clip");
        assert_eq!(
            capture.authority_paths.as_deref(),
            Some(&[path.to_string_lossy().into_owned()][..])
        );
        assert_eq!(capture.preview, path.to_string_lossy());
    }

    #[test]
    fn a_directory_clip_refines_to_directory() {
        let dir = crate::testutil::tempdir("capture-dir");
        let mut snap = Snapshot {
            item_utis: vec!["public.file-url".to_string()],
            ..Default::default()
        };
        snap.data.insert(
            "public.file-url".to_string(),
            format!("file://{}", dir.path().display()).into_bytes(),
        );
        snap.frontmost = text_snapshot("x").frontmost;
        snap.resolved_url_path = Some(dir.path().to_string_lossy().into_owned());
        let capture = decide(&snap).expect("captured");
        assert_eq!(capture.kind, TypeKind::Directory);
    }

    #[test]
    fn a_multi_file_clip_stays_files_with_a_path_preview_and_full_authority() {
        let paths = vec!["/tmp/a.txt".to_string(), "/tmp/b.txt".to_string()];
        let mut snap = Snapshot {
            item_utis: vec!["NSFilenamesPboardType".to_string()],
            ..Default::default()
        };
        snap.data
            .insert("NSFilenamesPboardType".to_string(), b"plist".to_vec());
        snap.frontmost = text_snapshot("x").frontmost;
        snap.filenames = Some(paths.clone());
        let capture = decide(&snap).expect("captured");
        assert_eq!(capture.kind, TypeKind::Files);
        assert_eq!(capture.preview, "/tmp/a.txt\n/tmp/b.txt");
        assert_eq!(capture.authority_paths.as_deref(), Some(&paths[..]));
    }

    #[test]
    fn an_unresolvable_single_file_list_path_keeps_authority() {
        // classify_file_or_directory fails (no resolved path), but a parseable
        // one-entry file list stays authoritative, per the Lua's elseif.
        let mut snap = Snapshot {
            item_utis: vec!["NSFilenamesPboardType".to_string()],
            ..Default::default()
        };
        snap.data
            .insert("NSFilenamesPboardType".to_string(), b"plist".to_vec());
        snap.frontmost = text_snapshot("x").frontmost;
        snap.filenames = Some(vec!["/tmp/only.txt".to_string()]);
        let capture = decide(&snap).expect("captured");
        assert_eq!(capture.kind, TypeKind::Files);
        assert_eq!(
            capture.authority_paths.as_deref(),
            Some(&["/tmp/only.txt".to_string()][..])
        );
    }

    #[test]
    fn previews_flatten_trim_and_truncate_on_codepoint_boundaries() {
        assert_eq!(preview_of("  \n\n  first  \r\n second\n"), "first second");
        // "éa" is 3 bytes, so byte 100 of 40 repeats falls inside the é of the
        // 34th repeat (99 = 33 × 3) and the cut must back off to 99 bytes.
        let long = "éa".repeat(40);
        let flattened = preview_of(&long);
        assert!(flattened.ends_with('…'));
        assert_eq!(flattened.trim_end_matches('…').len(), 99);
    }

    #[test]
    fn files_previews_keep_whole_paths_and_summarize_the_rest() {
        let paths: Vec<String> = (0..5)
            .map(|i| format!("/tmp/dir/file-{i:02}.txt"))
            .collect();
        let preview = files_preview(&paths);
        assert!(preview.ends_with("more"), "preview {preview:?}");
        assert!(preview.contains("/tmp/dir/file-00.txt"));
        let single_huge = vec![format!("/tmp/{}", "x".repeat(200))];
        let preview = files_preview(&single_huge);
        assert!(preview.starts_with("/tmp/"));
        assert!(preview.contains("+0 more"));
    }

    #[test]
    fn the_bare_url_heuristic_matches_the_lua_pattern() {
        assert!(looks_like_bare_url("https://x"));
        assert!(looks_like_bare_url("  x-scheme+a.b://path  "));
        assert!(!looks_like_bare_url("https://"));
        assert!(!looks_like_bare_url("https://a b"));
        assert!(!looks_like_bare_url("1https://x"));
        assert!(!looks_like_bare_url("no url here"));
    }

    #[test]
    fn tag_stripping_unescapes_in_the_lua_replacement_order() {
        assert_eq!(strip_html_tags("<b>hi</b> &amp; bye"), "hi & bye");
        assert_eq!(
            strip_html_tags("&amp;lt;"),
            "<",
            "&amp; replaced first, as the Lua does"
        );
        assert_eq!(strip_html_tags("a <unclosed"), "a <unclosed");
    }
}
