[style.description]
foreground = { ansi = 8 }
underline = false
bold = false
italic = false

[style.command_name]
foreground = { ansi = 15 }
underline = false
bold = false
italic = false

[style.example_text]
underline = false
bold = false
italic = true

[style.example_code]
foreground = { rgb = { r = 0, g = 135, b = 175 } }
underline = false
bold = false
italic = false

[style.example_variable]
foreground = { rgb = { r = 255, g = 175, b = 1 } }
underline = false
bold = false
italic = true

[display]
compact = false
use_pager = true

[updates]
auto_update = true
auto_update_interval_hours = 168

[directories]
cache_dir = "~/.cache/tealdeer"
custom_pages_dir = "~/.local/share/tealdeer/pages"
